// Contrato del core bancario de AIBank.
//
// Fuente de verdad de la frontera entre el core (Rust) y los adaptadores (Go).
// Un cambio incompatible aquí rompe la compilación de ambos lados, no la producción.
//
// Reglas del contrato:
//   - El dinero SIEMPRE viaja como entero en micras (millonésimas, 10^-6) + moneda.
//     Nunca punto flotante, nunca decimales en texto.
//   - Toda escritura lleva idempotency_key: los rieles y las redes de tarjetas
//     reintentan, y el efecto debe ocurrir exactamente una vez.
//   - Los errores de negocio viajan con un PostingErrorReason en la metadata
//     `x-aibank-reason`, para que el llamador distinga "fondos insuficientes"
//     (definitivo, no reintentar) de "base no disponible" (reintentable).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: aibank/core/v1/core.proto

package corev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LedgerService_Post_FullMethodName        = "/aibank.core.v1.LedgerService/Post"
	LedgerService_GetBalance_FullMethodName  = "/aibank.core.v1.LedgerService/GetBalance"
	LedgerService_ListEntries_FullMethodName = "/aibank.core.v1.LedgerService/ListEntries"
)

// LedgerServiceClient is the client API for LedgerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LedgerServiceClient interface {
	// Única vía de escritura al ledger. Idempotente por `idempotency_key`.
	Post(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error)
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
	// Extracto de una cuenta, del movimiento más reciente al más antiguo.
	ListEntries(ctx context.Context, in *ListEntriesRequest, opts ...grpc.CallOption) (*ListEntriesResponse, error)
}

type ledgerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLedgerServiceClient(cc grpc.ClientConnInterface) LedgerServiceClient {
	return &ledgerServiceClient{cc}
}

func (c *ledgerServiceClient) Post(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, LedgerService_Post_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, LedgerService_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) ListEntries(ctx context.Context, in *ListEntriesRequest, opts ...grpc.CallOption) (*ListEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEntriesResponse)
	err := c.cc.Invoke(ctx, LedgerService_ListEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LedgerServiceServer is the server API for LedgerService service.
// All implementations must embed UnimplementedLedgerServiceServer
// for forward compatibility.
type LedgerServiceServer interface {
	// Única vía de escritura al ledger. Idempotente por `idempotency_key`.
	Post(context.Context, *PostRequest) (*PostResponse, error)
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
	// Extracto de una cuenta, del movimiento más reciente al más antiguo.
	ListEntries(context.Context, *ListEntriesRequest) (*ListEntriesResponse, error)
	mustEmbedUnimplementedLedgerServiceServer()
}

// UnimplementedLedgerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLedgerServiceServer struct{}

func (UnimplementedLedgerServiceServer) Post(context.Context, *PostRequest) (*PostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Post not implemented")
}
func (UnimplementedLedgerServiceServer) GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedLedgerServiceServer) ListEntries(context.Context, *ListEntriesRequest) (*ListEntriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEntries not implemented")
}
func (UnimplementedLedgerServiceServer) mustEmbedUnimplementedLedgerServiceServer() {}
func (UnimplementedLedgerServiceServer) testEmbeddedByValue()                       {}

// UnsafeLedgerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LedgerServiceServer will
// result in compilation errors.
type UnsafeLedgerServiceServer interface {
	mustEmbedUnimplementedLedgerServiceServer()
}

func RegisterLedgerServiceServer(s grpc.ServiceRegistrar, srv LedgerServiceServer) {
	// If the following call panics, it indicates UnimplementedLedgerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LedgerService_ServiceDesc, srv)
}

func _LedgerService_Post_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).Post(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_Post_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).Post(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_ListEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).ListEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_ListEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).ListEntries(ctx, req.(*ListEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LedgerService_ServiceDesc is the grpc.ServiceDesc for LedgerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LedgerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aibank.core.v1.LedgerService",
	HandlerType: (*LedgerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Post",
			Handler:    _LedgerService_Post_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _LedgerService_GetBalance_Handler,
		},
		{
			MethodName: "ListEntries",
			Handler:    _LedgerService_ListEntries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aibank/core/v1/core.proto",
}

const (
	AccountService_OpenCustomerAccount_FullMethodName   = "/aibank.core.v1.AccountService/OpenCustomerAccount"
	AccountService_CreateInternalAccount_FullMethodName = "/aibank.core.v1.AccountService/CreateInternalAccount"
	AccountService_GetAccount_FullMethodName            = "/aibank.core.v1.AccountService/GetAccount"
	AccountService_GetAccountById_FullMethodName        = "/aibank.core.v1.AccountService/GetAccountById"
)

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountServiceClient interface {
	OpenCustomerAccount(ctx context.Context, in *OpenCustomerAccountRequest, opts ...grpc.CallOption) (*Account, error)
	CreateInternalAccount(ctx context.Context, in *CreateInternalAccountRequest, opts ...grpc.CallOption) (*Account, error)
	GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*Account, error)
	GetAccountById(ctx context.Context, in *GetAccountByIdRequest, opts ...grpc.CallOption) (*Account, error)
}

type accountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountServiceClient(cc grpc.ClientConnInterface) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) OpenCustomerAccount(ctx context.Context, in *OpenCustomerAccountRequest, opts ...grpc.CallOption) (*Account, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Account)
	err := c.cc.Invoke(ctx, AccountService_OpenCustomerAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) CreateInternalAccount(ctx context.Context, in *CreateInternalAccountRequest, opts ...grpc.CallOption) (*Account, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Account)
	err := c.cc.Invoke(ctx, AccountService_CreateInternalAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*Account, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Account)
	err := c.cc.Invoke(ctx, AccountService_GetAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetAccountById(ctx context.Context, in *GetAccountByIdRequest, opts ...grpc.CallOption) (*Account, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Account)
	err := c.cc.Invoke(ctx, AccountService_GetAccountById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
// All implementations must embed UnimplementedAccountServiceServer
// for forward compatibility.
type AccountServiceServer interface {
	OpenCustomerAccount(context.Context, *OpenCustomerAccountRequest) (*Account, error)
	CreateInternalAccount(context.Context, *CreateInternalAccountRequest) (*Account, error)
	GetAccount(context.Context, *GetAccountRequest) (*Account, error)
	GetAccountById(context.Context, *GetAccountByIdRequest) (*Account, error)
	mustEmbedUnimplementedAccountServiceServer()
}

// UnimplementedAccountServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountServiceServer struct{}

func (UnimplementedAccountServiceServer) OpenCustomerAccount(context.Context, *OpenCustomerAccountRequest) (*Account, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenCustomerAccount not implemented")
}
func (UnimplementedAccountServiceServer) CreateInternalAccount(context.Context, *CreateInternalAccountRequest) (*Account, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateInternalAccount not implemented")
}
func (UnimplementedAccountServiceServer) GetAccount(context.Context, *GetAccountRequest) (*Account, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccount not implemented")
}
func (UnimplementedAccountServiceServer) GetAccountById(context.Context, *GetAccountByIdRequest) (*Account, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccountById not implemented")
}
func (UnimplementedAccountServiceServer) mustEmbedUnimplementedAccountServiceServer() {}
func (UnimplementedAccountServiceServer) testEmbeddedByValue()                        {}

// UnsafeAccountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountServiceServer will
// result in compilation errors.
type UnsafeAccountServiceServer interface {
	mustEmbedUnimplementedAccountServiceServer()
}

func RegisterAccountServiceServer(s grpc.ServiceRegistrar, srv AccountServiceServer) {
	// If the following call panics, it indicates UnimplementedAccountServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountService_ServiceDesc, srv)
}

func _AccountService_OpenCustomerAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenCustomerAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).OpenCustomerAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_OpenCustomerAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).OpenCustomerAccount(ctx, req.(*OpenCustomerAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_CreateInternalAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInternalAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).CreateInternalAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_CreateInternalAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).CreateInternalAccount(ctx, req.(*CreateInternalAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetAccount(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetAccountById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetAccountById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetAccountById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetAccountById(ctx, req.(*GetAccountByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountService_ServiceDesc is the grpc.ServiceDesc for AccountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aibank.core.v1.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenCustomerAccount",
			Handler:    _AccountService_OpenCustomerAccount_Handler,
		},
		{
			MethodName: "CreateInternalAccount",
			Handler:    _AccountService_CreateInternalAccount_Handler,
		},
		{
			MethodName: "GetAccount",
			Handler:    _AccountService_GetAccount_Handler,
		},
		{
			MethodName: "GetAccountById",
			Handler:    _AccountService_GetAccountById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aibank/core/v1/core.proto",
}

const (
	ProductService_CreateProduct_FullMethodName = "/aibank.core.v1.ProductService/CreateProduct"
	ProductService_GetProduct_FullMethodName    = "/aibank.core.v1.ProductService/GetProduct"
)

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductServiceClient interface {
	CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*Product, error)
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*Product, error)
}

type productServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductServiceClient(cc grpc.ClientConnInterface) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*Product, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Product)
	err := c.cc.Invoke(ctx, ProductService_CreateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*Product, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Product)
	err := c.cc.Invoke(ctx, ProductService_GetProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
// All implementations must embed UnimplementedProductServiceServer
// for forward compatibility.
type ProductServiceServer interface {
	CreateProduct(context.Context, *CreateProductRequest) (*Product, error)
	GetProduct(context.Context, *GetProductRequest) (*Product, error)
	mustEmbedUnimplementedProductServiceServer()
}

// UnimplementedProductServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductServiceServer struct{}

func (UnimplementedProductServiceServer) CreateProduct(context.Context, *CreateProductRequest) (*Product, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProduct not implemented")
}
func (UnimplementedProductServiceServer) GetProduct(context.Context, *GetProductRequest) (*Product, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedProductServiceServer) mustEmbedUnimplementedProductServiceServer() {}
func (UnimplementedProductServiceServer) testEmbeddedByValue()                        {}

// UnsafeProductServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductServiceServer will
// result in compilation errors.
type UnsafeProductServiceServer interface {
	mustEmbedUnimplementedProductServiceServer()
}

func RegisterProductServiceServer(s grpc.ServiceRegistrar, srv ProductServiceServer) {
	// If the following call panics, it indicates UnimplementedProductServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductService_ServiceDesc, srv)
}

func _ProductService_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_CreateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreateProduct(ctx, req.(*CreateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductService_ServiceDesc is the grpc.ServiceDesc for ProductService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aibank.core.v1.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProduct",
			Handler:    _ProductService_CreateProduct_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _ProductService_GetProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aibank/core/v1/core.proto",
}

const (
	ReconciliationService_ListOpenFindings_FullMethodName = "/aibank.core.v1.ReconciliationService/ListOpenFindings"
	ReconciliationService_ResolveFinding_FullMethodName   = "/aibank.core.v1.ReconciliationService/ResolveFinding"
	ReconciliationService_RunInternalCheck_FullMethodName = "/aibank.core.v1.ReconciliationService/RunInternalCheck"
)

// ReconciliationServiceClient is the client API for ReconciliationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReconciliationServiceClient interface {
	// Diferencias abiertas, para la cola de operaciones.
	ListOpenFindings(ctx context.Context, in *ListOpenFindingsRequest, opts ...grpc.CallOption) (*ListOpenFindingsResponse, error)
	// Cierra una diferencia dejando constancia.
	ResolveFinding(ctx context.Context, in *ResolveFindingRequest, opts ...grpc.CallOption) (*ResolveFindingResponse, error)
	// Dispara la conciliación interna bajo demanda.
	RunInternalCheck(ctx context.Context, in *RunInternalCheckRequest, opts ...grpc.CallOption) (*RunInternalCheckResponse, error)
}

type reconciliationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReconciliationServiceClient(cc grpc.ClientConnInterface) ReconciliationServiceClient {
	return &reconciliationServiceClient{cc}
}

func (c *reconciliationServiceClient) ListOpenFindings(ctx context.Context, in *ListOpenFindingsRequest, opts ...grpc.CallOption) (*ListOpenFindingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOpenFindingsResponse)
	err := c.cc.Invoke(ctx, ReconciliationService_ListOpenFindings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reconciliationServiceClient) ResolveFinding(ctx context.Context, in *ResolveFindingRequest, opts ...grpc.CallOption) (*ResolveFindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveFindingResponse)
	err := c.cc.Invoke(ctx, ReconciliationService_ResolveFinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reconciliationServiceClient) RunInternalCheck(ctx context.Context, in *RunInternalCheckRequest, opts ...grpc.CallOption) (*RunInternalCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunInternalCheckResponse)
	err := c.cc.Invoke(ctx, ReconciliationService_RunInternalCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReconciliationServiceServer is the server API for ReconciliationService service.
// All implementations must embed UnimplementedReconciliationServiceServer
// for forward compatibility.
type ReconciliationServiceServer interface {
	// Diferencias abiertas, para la cola de operaciones.
	ListOpenFindings(context.Context, *ListOpenFindingsRequest) (*ListOpenFindingsResponse, error)
	// Cierra una diferencia dejando constancia.
	ResolveFinding(context.Context, *ResolveFindingRequest) (*ResolveFindingResponse, error)
	// Dispara la conciliación interna bajo demanda.
	RunInternalCheck(context.Context, *RunInternalCheckRequest) (*RunInternalCheckResponse, error)
	mustEmbedUnimplementedReconciliationServiceServer()
}

// UnimplementedReconciliationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReconciliationServiceServer struct{}

func (UnimplementedReconciliationServiceServer) ListOpenFindings(context.Context, *ListOpenFindingsRequest) (*ListOpenFindingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOpenFindings not implemented")
}
func (UnimplementedReconciliationServiceServer) ResolveFinding(context.Context, *ResolveFindingRequest) (*ResolveFindingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveFinding not implemented")
}
func (UnimplementedReconciliationServiceServer) RunInternalCheck(context.Context, *RunInternalCheckRequest) (*RunInternalCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunInternalCheck not implemented")
}
func (UnimplementedReconciliationServiceServer) mustEmbedUnimplementedReconciliationServiceServer() {}
func (UnimplementedReconciliationServiceServer) testEmbeddedByValue()                               {}

// UnsafeReconciliationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReconciliationServiceServer will
// result in compilation errors.
type UnsafeReconciliationServiceServer interface {
	mustEmbedUnimplementedReconciliationServiceServer()
}

func RegisterReconciliationServiceServer(s grpc.ServiceRegistrar, srv ReconciliationServiceServer) {
	// If the following call panics, it indicates UnimplementedReconciliationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReconciliationService_ServiceDesc, srv)
}

func _ReconciliationService_ListOpenFindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOpenFindingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReconciliationServiceServer).ListOpenFindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReconciliationService_ListOpenFindings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReconciliationServiceServer).ListOpenFindings(ctx, req.(*ListOpenFindingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReconciliationService_ResolveFinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveFindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReconciliationServiceServer).ResolveFinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReconciliationService_ResolveFinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReconciliationServiceServer).ResolveFinding(ctx, req.(*ResolveFindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReconciliationService_RunInternalCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunInternalCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReconciliationServiceServer).RunInternalCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReconciliationService_RunInternalCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReconciliationServiceServer).RunInternalCheck(ctx, req.(*RunInternalCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReconciliationService_ServiceDesc is the grpc.ServiceDesc for ReconciliationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReconciliationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aibank.core.v1.ReconciliationService",
	HandlerType: (*ReconciliationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListOpenFindings",
			Handler:    _ReconciliationService_ListOpenFindings_Handler,
		},
		{
			MethodName: "ResolveFinding",
			Handler:    _ReconciliationService_ResolveFinding_Handler,
		},
		{
			MethodName: "RunInternalCheck",
			Handler:    _ReconciliationService_RunInternalCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aibank/core/v1/core.proto",
}

const (
	AuthorizationService_Authorize_FullMethodName        = "/aibank.core.v1.AuthorizationService/Authorize"
	AuthorizationService_Capture_FullMethodName          = "/aibank.core.v1.AuthorizationService/Capture"
	AuthorizationService_Refund_FullMethodName           = "/aibank.core.v1.AuthorizationService/Refund"
	AuthorizationService_GetAuthorization_FullMethodName = "/aibank.core.v1.AuthorizationService/GetAuthorization"
	AuthorizationService_ReleaseExpired_FullMethodName   = "/aibank.core.v1.AuthorizationService/ReleaseExpired"
)

// AuthorizationServiceClient is the client API for AuthorizationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthorizationServiceClient interface {
	// Retiene el monto en la cuenta pagadora. Idempotente por `idempotency_key`.
	Authorize(ctx context.Context, in *AuthorizeRequest, opts ...grpc.CallOption) (*AuthorizeResponse, error)
	// Liquida la retención al receptor. Idempotente por naturaleza: capturar dos
	// veces devuelve la misma captura, con el mismo `settled_at`.
	Capture(ctx context.Context, in *CaptureRequest, opts ...grpc.CallOption) (*Authorization, error)
	// Devuelve dinero ya capturado al pagador.
	Refund(ctx context.Context, in *RefundRequest, opts ...grpc.CallOption) (*Authorization, error)
	GetAuthorization(ctx context.Context, in *GetAuthorizationRequest, opts ...grpc.CallOption) (*Authorization, error)
	// Libera las retenciones vencidas. La invoca un proceso periódico.
	ReleaseExpired(ctx context.Context, in *ReleaseExpiredRequest, opts ...grpc.CallOption) (*ReleaseExpiredResponse, error)
}

type authorizationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthorizationServiceClient(cc grpc.ClientConnInterface) AuthorizationServiceClient {
	return &authorizationServiceClient{cc}
}

func (c *authorizationServiceClient) Authorize(ctx context.Context, in *AuthorizeRequest, opts ...grpc.CallOption) (*AuthorizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizeResponse)
	err := c.cc.Invoke(ctx, AuthorizationService_Authorize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationServiceClient) Capture(ctx context.Context, in *CaptureRequest, opts ...grpc.CallOption) (*Authorization, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Authorization)
	err := c.cc.Invoke(ctx, AuthorizationService_Capture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationServiceClient) Refund(ctx context.Context, in *RefundRequest, opts ...grpc.CallOption) (*Authorization, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Authorization)
	err := c.cc.Invoke(ctx, AuthorizationService_Refund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationServiceClient) GetAuthorization(ctx context.Context, in *GetAuthorizationRequest, opts ...grpc.CallOption) (*Authorization, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Authorization)
	err := c.cc.Invoke(ctx, AuthorizationService_GetAuthorization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationServiceClient) ReleaseExpired(ctx context.Context, in *ReleaseExpiredRequest, opts ...grpc.CallOption) (*ReleaseExpiredResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseExpiredResponse)
	err := c.cc.Invoke(ctx, AuthorizationService_ReleaseExpired_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthorizationServiceServer is the server API for AuthorizationService service.
// All implementations must embed UnimplementedAuthorizationServiceServer
// for forward compatibility.
type AuthorizationServiceServer interface {
	// Retiene el monto en la cuenta pagadora. Idempotente por `idempotency_key`.
	Authorize(context.Context, *AuthorizeRequest) (*AuthorizeResponse, error)
	// Liquida la retención al receptor. Idempotente por naturaleza: capturar dos
	// veces devuelve la misma captura, con el mismo `settled_at`.
	Capture(context.Context, *CaptureRequest) (*Authorization, error)
	// Devuelve dinero ya capturado al pagador.
	Refund(context.Context, *RefundRequest) (*Authorization, error)
	GetAuthorization(context.Context, *GetAuthorizationRequest) (*Authorization, error)
	// Libera las retenciones vencidas. La invoca un proceso periódico.
	ReleaseExpired(context.Context, *ReleaseExpiredRequest) (*ReleaseExpiredResponse, error)
	mustEmbedUnimplementedAuthorizationServiceServer()
}

// UnimplementedAuthorizationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthorizationServiceServer struct{}

func (UnimplementedAuthorizationServiceServer) Authorize(context.Context, *AuthorizeRequest) (*AuthorizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Authorize not implemented")
}
func (UnimplementedAuthorizationServiceServer) Capture(context.Context, *CaptureRequest) (*Authorization, error) {
	return nil, status.Error(codes.Unimplemented, "method Capture not implemented")
}
func (UnimplementedAuthorizationServiceServer) Refund(context.Context, *RefundRequest) (*Authorization, error) {
	return nil, status.Error(codes.Unimplemented, "method Refund not implemented")
}
func (UnimplementedAuthorizationServiceServer) GetAuthorization(context.Context, *GetAuthorizationRequest) (*Authorization, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuthorization not implemented")
}
func (UnimplementedAuthorizationServiceServer) ReleaseExpired(context.Context, *ReleaseExpiredRequest) (*ReleaseExpiredResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseExpired not implemented")
}
func (UnimplementedAuthorizationServiceServer) mustEmbedUnimplementedAuthorizationServiceServer() {}
func (UnimplementedAuthorizationServiceServer) testEmbeddedByValue()                              {}

// UnsafeAuthorizationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthorizationServiceServer will
// result in compilation errors.
type UnsafeAuthorizationServiceServer interface {
	mustEmbedUnimplementedAuthorizationServiceServer()
}

func RegisterAuthorizationServiceServer(s grpc.ServiceRegistrar, srv AuthorizationServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthorizationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthorizationService_ServiceDesc, srv)
}

func _AuthorizationService_Authorize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServiceServer).Authorize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthorizationService_Authorize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServiceServer).Authorize(ctx, req.(*AuthorizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorizationService_Capture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServiceServer).Capture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthorizationService_Capture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServiceServer).Capture(ctx, req.(*CaptureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorizationService_Refund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServiceServer).Refund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthorizationService_Refund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServiceServer).Refund(ctx, req.(*RefundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorizationService_GetAuthorization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthorizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServiceServer).GetAuthorization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthorizationService_GetAuthorization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServiceServer).GetAuthorization(ctx, req.(*GetAuthorizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorizationService_ReleaseExpired_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseExpiredRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServiceServer).ReleaseExpired(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthorizationService_ReleaseExpired_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServiceServer).ReleaseExpired(ctx, req.(*ReleaseExpiredRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthorizationService_ServiceDesc is the grpc.ServiceDesc for AuthorizationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthorizationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aibank.core.v1.AuthorizationService",
	HandlerType: (*AuthorizationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authorize",
			Handler:    _AuthorizationService_Authorize_Handler,
		},
		{
			MethodName: "Capture",
			Handler:    _AuthorizationService_Capture_Handler,
		},
		{
			MethodName: "Refund",
			Handler:    _AuthorizationService_Refund_Handler,
		},
		{
			MethodName: "GetAuthorization",
			Handler:    _AuthorizationService_GetAuthorization_Handler,
		},
		{
			MethodName: "ReleaseExpired",
			Handler:    _AuthorizationService_ReleaseExpired_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aibank/core/v1/core.proto",
}

const (
	MandateService_GrantMandate_FullMethodName          = "/aibank.core.v1.MandateService/GrantMandate"
	MandateService_RevokeMandate_FullMethodName         = "/aibank.core.v1.MandateService/RevokeMandate"
	MandateService_GetMandate_FullMethodName            = "/aibank.core.v1.MandateService/GetMandate"
	MandateService_FindActiveMandate_FullMethodName     = "/aibank.core.v1.MandateService/FindActiveMandate"
	MandateService_ListMandates_FullMethodName          = "/aibank.core.v1.MandateService/ListMandates"
	MandateService_AuthorizeUnderMandate_FullMethodName = "/aibank.core.v1.MandateService/AuthorizeUnderMandate"
)

// MandateServiceClient is the client API for MandateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MandateServiceClient interface {
	// Registra el permiso que un titular otorgó tras autenticarse.
	GrantMandate(ctx context.Context, in *GrantMandateRequest, opts ...grpc.CallOption) (*Mandate, error)
	// Retira el permiso. Idempotente. No cancela las retenciones ya vivas.
	RevokeMandate(ctx context.Context, in *RevokeMandateRequest, opts ...grpc.CallOption) (*Mandate, error)
	GetMandate(ctx context.Context, in *GetMandateRequest, opts ...grpc.CallOption) (*Mandate, error)
	// Permiso vivo de una integración sobre una cuenta. NOT_FOUND si no hay.
	FindActiveMandate(ctx context.Context, in *FindActiveMandateRequest, opts ...grpc.CallOption) (*Mandate, error)
	// Mandatos de un titular, para que los vea y los revoque en su app.
	ListMandates(ctx context.Context, in *ListMandatesRequest, opts ...grpc.CallOption) (*ListMandatesResponse, error)
	// Inicia un pago bajo un mandato: comprueba el permiso y retiene en la misma
	// transacción.
	AuthorizeUnderMandate(ctx context.Context, in *AuthorizeUnderMandateRequest, opts ...grpc.CallOption) (*AuthorizeUnderMandateResponse, error)
}

type mandateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMandateServiceClient(cc grpc.ClientConnInterface) MandateServiceClient {
	return &mandateServiceClient{cc}
}

func (c *mandateServiceClient) GrantMandate(ctx context.Context, in *GrantMandateRequest, opts ...grpc.CallOption) (*Mandate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Mandate)
	err := c.cc.Invoke(ctx, MandateService_GrantMandate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mandateServiceClient) RevokeMandate(ctx context.Context, in *RevokeMandateRequest, opts ...grpc.CallOption) (*Mandate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Mandate)
	err := c.cc.Invoke(ctx, MandateService_RevokeMandate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mandateServiceClient) GetMandate(ctx context.Context, in *GetMandateRequest, opts ...grpc.CallOption) (*Mandate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Mandate)
	err := c.cc.Invoke(ctx, MandateService_GetMandate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mandateServiceClient) FindActiveMandate(ctx context.Context, in *FindActiveMandateRequest, opts ...grpc.CallOption) (*Mandate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Mandate)
	err := c.cc.Invoke(ctx, MandateService_FindActiveMandate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mandateServiceClient) ListMandates(ctx context.Context, in *ListMandatesRequest, opts ...grpc.CallOption) (*ListMandatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMandatesResponse)
	err := c.cc.Invoke(ctx, MandateService_ListMandates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mandateServiceClient) AuthorizeUnderMandate(ctx context.Context, in *AuthorizeUnderMandateRequest, opts ...grpc.CallOption) (*AuthorizeUnderMandateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizeUnderMandateResponse)
	err := c.cc.Invoke(ctx, MandateService_AuthorizeUnderMandate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MandateServiceServer is the server API for MandateService service.
// All implementations must embed UnimplementedMandateServiceServer
// for forward compatibility.
type MandateServiceServer interface {
	// Registra el permiso que un titular otorgó tras autenticarse.
	GrantMandate(context.Context, *GrantMandateRequest) (*Mandate, error)
	// Retira el permiso. Idempotente. No cancela las retenciones ya vivas.
	RevokeMandate(context.Context, *RevokeMandateRequest) (*Mandate, error)
	GetMandate(context.Context, *GetMandateRequest) (*Mandate, error)
	// Permiso vivo de una integración sobre una cuenta. NOT_FOUND si no hay.
	FindActiveMandate(context.Context, *FindActiveMandateRequest) (*Mandate, error)
	// Mandatos de un titular, para que los vea y los revoque en su app.
	ListMandates(context.Context, *ListMandatesRequest) (*ListMandatesResponse, error)
	// Inicia un pago bajo un mandato: comprueba el permiso y retiene en la misma
	// transacción.
	AuthorizeUnderMandate(context.Context, *AuthorizeUnderMandateRequest) (*AuthorizeUnderMandateResponse, error)
	mustEmbedUnimplementedMandateServiceServer()
}

// UnimplementedMandateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMandateServiceServer struct{}

func (UnimplementedMandateServiceServer) GrantMandate(context.Context, *GrantMandateRequest) (*Mandate, error) {
	return nil, status.Error(codes.Unimplemented, "method GrantMandate not implemented")
}
func (UnimplementedMandateServiceServer) RevokeMandate(context.Context, *RevokeMandateRequest) (*Mandate, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeMandate not implemented")
}
func (UnimplementedMandateServiceServer) GetMandate(context.Context, *GetMandateRequest) (*Mandate, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMandate not implemented")
}
func (UnimplementedMandateServiceServer) FindActiveMandate(context.Context, *FindActiveMandateRequest) (*Mandate, error) {
	return nil, status.Error(codes.Unimplemented, "method FindActiveMandate not implemented")
}
func (UnimplementedMandateServiceServer) ListMandates(context.Context, *ListMandatesRequest) (*ListMandatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMandates not implemented")
}
func (UnimplementedMandateServiceServer) AuthorizeUnderMandate(context.Context, *AuthorizeUnderMandateRequest) (*AuthorizeUnderMandateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthorizeUnderMandate not implemented")
}
func (UnimplementedMandateServiceServer) mustEmbedUnimplementedMandateServiceServer() {}
func (UnimplementedMandateServiceServer) testEmbeddedByValue()                        {}

// UnsafeMandateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MandateServiceServer will
// result in compilation errors.
type UnsafeMandateServiceServer interface {
	mustEmbedUnimplementedMandateServiceServer()
}

func RegisterMandateServiceServer(s grpc.ServiceRegistrar, srv MandateServiceServer) {
	// If the following call panics, it indicates UnimplementedMandateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MandateService_ServiceDesc, srv)
}

func _MandateService_GrantMandate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantMandateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MandateServiceServer).GrantMandate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MandateService_GrantMandate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MandateServiceServer).GrantMandate(ctx, req.(*GrantMandateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MandateService_RevokeMandate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeMandateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MandateServiceServer).RevokeMandate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MandateService_RevokeMandate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MandateServiceServer).RevokeMandate(ctx, req.(*RevokeMandateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MandateService_GetMandate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMandateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MandateServiceServer).GetMandate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MandateService_GetMandate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MandateServiceServer).GetMandate(ctx, req.(*GetMandateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MandateService_FindActiveMandate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindActiveMandateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MandateServiceServer).FindActiveMandate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MandateService_FindActiveMandate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MandateServiceServer).FindActiveMandate(ctx, req.(*FindActiveMandateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MandateService_ListMandates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMandatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MandateServiceServer).ListMandates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MandateService_ListMandates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MandateServiceServer).ListMandates(ctx, req.(*ListMandatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MandateService_AuthorizeUnderMandate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeUnderMandateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MandateServiceServer).AuthorizeUnderMandate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MandateService_AuthorizeUnderMandate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MandateServiceServer).AuthorizeUnderMandate(ctx, req.(*AuthorizeUnderMandateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MandateService_ServiceDesc is the grpc.ServiceDesc for MandateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MandateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aibank.core.v1.MandateService",
	HandlerType: (*MandateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GrantMandate",
			Handler:    _MandateService_GrantMandate_Handler,
		},
		{
			MethodName: "RevokeMandate",
			Handler:    _MandateService_RevokeMandate_Handler,
		},
		{
			MethodName: "GetMandate",
			Handler:    _MandateService_GetMandate_Handler,
		},
		{
			MethodName: "FindActiveMandate",
			Handler:    _MandateService_FindActiveMandate_Handler,
		},
		{
			MethodName: "ListMandates",
			Handler:    _MandateService_ListMandates_Handler,
		},
		{
			MethodName: "AuthorizeUnderMandate",
			Handler:    _MandateService_AuthorizeUnderMandate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aibank/core/v1/core.proto",
}
