// Contrato del core bancario de AIBank.
//
// Fuente de verdad de la frontera entre el core (Rust) y los adaptadores (Go).
// Un cambio incompatible aquí rompe la compilación de ambos lados, no la producción.
//
// Reglas del contrato:
//   - El dinero SIEMPRE viaja como entero en micras (millonésimas, 10^-6) + moneda.
//     Nunca punto flotante, nunca decimales en texto.
//   - Toda escritura lleva idempotency_key: los rieles y las redes de tarjetas
//     reintentan, y el efecto debe ocurrir exactamente una vez.
//   - Los errores de negocio viajan con un PostingErrorReason en la metadata
//     `x-aibank-reason`, para que el llamador distinga "fondos insuficientes"
//     (definitivo, no reintentar) de "base no disponible" (reintentable).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: aibank/core/v1/core.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Direction int32

const (
	Direction_DIRECTION_UNSPECIFIED Direction = 0
	Direction_DIRECTION_DEBIT       Direction = 1
	Direction_DIRECTION_CREDIT      Direction = 2
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "DIRECTION_UNSPECIFIED",
		1: "DIRECTION_DEBIT",
		2: "DIRECTION_CREDIT",
	}
	Direction_value = map[string]int32{
		"DIRECTION_UNSPECIFIED": 0,
		"DIRECTION_DEBIT":       1,
		"DIRECTION_CREDIT":      2,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_aibank_core_v1_core_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_aibank_core_v1_core_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{0}
}

type AccountType int32

const (
	AccountType_ACCOUNT_TYPE_UNSPECIFIED AccountType = 0
	AccountType_ACCOUNT_TYPE_ASSET       AccountType = 1
	AccountType_ACCOUNT_TYPE_LIABILITY   AccountType = 2
	AccountType_ACCOUNT_TYPE_EQUITY      AccountType = 3
	AccountType_ACCOUNT_TYPE_INCOME      AccountType = 4
	AccountType_ACCOUNT_TYPE_EXPENSE     AccountType = 5
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0: "ACCOUNT_TYPE_UNSPECIFIED",
		1: "ACCOUNT_TYPE_ASSET",
		2: "ACCOUNT_TYPE_LIABILITY",
		3: "ACCOUNT_TYPE_EQUITY",
		4: "ACCOUNT_TYPE_INCOME",
		5: "ACCOUNT_TYPE_EXPENSE",
	}
	AccountType_value = map[string]int32{
		"ACCOUNT_TYPE_UNSPECIFIED": 0,
		"ACCOUNT_TYPE_ASSET":       1,
		"ACCOUNT_TYPE_LIABILITY":   2,
		"ACCOUNT_TYPE_EQUITY":      3,
		"ACCOUNT_TYPE_INCOME":      4,
		"ACCOUNT_TYPE_EXPENSE":     5,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_aibank_core_v1_core_proto_enumTypes[1].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_aibank_core_v1_core_proto_enumTypes[1]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{1}
}

type AccountOwner int32

const (
	AccountOwner_ACCOUNT_OWNER_UNSPECIFIED AccountOwner = 0
	AccountOwner_ACCOUNT_OWNER_CUSTOMER    AccountOwner = 1
	AccountOwner_ACCOUNT_OWNER_INTERNAL    AccountOwner = 2
)

// Enum value maps for AccountOwner.
var (
	AccountOwner_name = map[int32]string{
		0: "ACCOUNT_OWNER_UNSPECIFIED",
		1: "ACCOUNT_OWNER_CUSTOMER",
		2: "ACCOUNT_OWNER_INTERNAL",
	}
	AccountOwner_value = map[string]int32{
		"ACCOUNT_OWNER_UNSPECIFIED": 0,
		"ACCOUNT_OWNER_CUSTOMER":    1,
		"ACCOUNT_OWNER_INTERNAL":    2,
	}
)

func (x AccountOwner) Enum() *AccountOwner {
	p := new(AccountOwner)
	*p = x
	return p
}

func (x AccountOwner) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountOwner) Descriptor() protoreflect.EnumDescriptor {
	return file_aibank_core_v1_core_proto_enumTypes[2].Descriptor()
}

func (AccountOwner) Type() protoreflect.EnumType {
	return &file_aibank_core_v1_core_proto_enumTypes[2]
}

func (x AccountOwner) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountOwner.Descriptor instead.
func (AccountOwner) EnumDescriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{2}
}

type AccountStatus int32

const (
	AccountStatus_ACCOUNT_STATUS_UNSPECIFIED AccountStatus = 0
	AccountStatus_ACCOUNT_STATUS_ACTIVE      AccountStatus = 1
	AccountStatus_ACCOUNT_STATUS_FROZEN      AccountStatus = 2
	AccountStatus_ACCOUNT_STATUS_CLOSED      AccountStatus = 3
)

// Enum value maps for AccountStatus.
var (
	AccountStatus_name = map[int32]string{
		0: "ACCOUNT_STATUS_UNSPECIFIED",
		1: "ACCOUNT_STATUS_ACTIVE",
		2: "ACCOUNT_STATUS_FROZEN",
		3: "ACCOUNT_STATUS_CLOSED",
	}
	AccountStatus_value = map[string]int32{
		"ACCOUNT_STATUS_UNSPECIFIED": 0,
		"ACCOUNT_STATUS_ACTIVE":      1,
		"ACCOUNT_STATUS_FROZEN":      2,
		"ACCOUNT_STATUS_CLOSED":      3,
	}
)

func (x AccountStatus) Enum() *AccountStatus {
	p := new(AccountStatus)
	*p = x
	return p
}

func (x AccountStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_aibank_core_v1_core_proto_enumTypes[3].Descriptor()
}

func (AccountStatus) Type() protoreflect.EnumType {
	return &file_aibank_core_v1_core_proto_enumTypes[3]
}

func (x AccountStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountStatus.Descriptor instead.
func (AccountStatus) EnumDescriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{3}
}

// Motivo de un rechazo. Viaja en la metadata `x-aibank-reason` junto al código gRPC.
type PostingErrorReason int32

const (
	PostingErrorReason_POSTING_ERROR_REASON_UNSPECIFIED PostingErrorReason = 0
	// La solicitud viola una regla del ledger (desbalance, monto <= 0, moneda).
	PostingErrorReason_POSTING_ERROR_REASON_INVALID PostingErrorReason = 1
	// La clave de idempotencia ya se usó con un payload distinto.
	PostingErrorReason_POSTING_ERROR_REASON_IDEMPOTENCY_CONFLICT PostingErrorReason = 2
	// La cuenta quedaría en negativo y el producto no admite sobregiro.
	PostingErrorReason_POSTING_ERROR_REASON_INSUFFICIENT_FUNDS PostingErrorReason = 3
	// El saldo superaría el tope regulatorio del producto.
	PostingErrorReason_POSTING_ERROR_REASON_BALANCE_CAP_EXCEEDED PostingErrorReason = 4
	// El monto supera el tope por operación del producto.
	PostingErrorReason_POSTING_ERROR_REASON_TRANSACTION_CAP_EXCEEDED PostingErrorReason = 5
	// Ya existe un registro con esa clave (código de cuenta o de producto repetido).
	PostingErrorReason_POSTING_ERROR_REASON_ALREADY_EXISTS PostingErrorReason = 6
)

// Enum value maps for PostingErrorReason.
var (
	PostingErrorReason_name = map[int32]string{
		0: "POSTING_ERROR_REASON_UNSPECIFIED",
		1: "POSTING_ERROR_REASON_INVALID",
		2: "POSTING_ERROR_REASON_IDEMPOTENCY_CONFLICT",
		3: "POSTING_ERROR_REASON_INSUFFICIENT_FUNDS",
		4: "POSTING_ERROR_REASON_BALANCE_CAP_EXCEEDED",
		5: "POSTING_ERROR_REASON_TRANSACTION_CAP_EXCEEDED",
		6: "POSTING_ERROR_REASON_ALREADY_EXISTS",
	}
	PostingErrorReason_value = map[string]int32{
		"POSTING_ERROR_REASON_UNSPECIFIED":              0,
		"POSTING_ERROR_REASON_INVALID":                  1,
		"POSTING_ERROR_REASON_IDEMPOTENCY_CONFLICT":     2,
		"POSTING_ERROR_REASON_INSUFFICIENT_FUNDS":       3,
		"POSTING_ERROR_REASON_BALANCE_CAP_EXCEEDED":     4,
		"POSTING_ERROR_REASON_TRANSACTION_CAP_EXCEEDED": 5,
		"POSTING_ERROR_REASON_ALREADY_EXISTS":           6,
	}
)

func (x PostingErrorReason) Enum() *PostingErrorReason {
	p := new(PostingErrorReason)
	*p = x
	return p
}

func (x PostingErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PostingErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_aibank_core_v1_core_proto_enumTypes[4].Descriptor()
}

func (PostingErrorReason) Type() protoreflect.EnumType {
	return &file_aibank_core_v1_core_proto_enumTypes[4]
}

func (x PostingErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PostingErrorReason.Descriptor instead.
func (PostingErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{4}
}

type FindingKind int32

const (
	FindingKind_FINDING_KIND_UNSPECIFIED FindingKind = 0
	// El saldo materializado no coincide con la suma de los asientos.
	FindingKind_FINDING_KIND_BALANCE_DRIFT FindingKind = 1
	// El proveedor reporta un movimiento que no está en el ledger.
	FindingKind_FINDING_KIND_MISSING_IN_LEDGER FindingKind = 2
	// El ledger registra un movimiento que el proveedor no reporta.
	FindingKind_FINDING_KIND_MISSING_AT_PROVIDER FindingKind = 3
	// Ambos lo tienen, por importes distintos.
	FindingKind_FINDING_KIND_AMOUNT_MISMATCH FindingKind = 4
	// Dinero detenido en tránsito o retención más allá del plazo razonable.
	FindingKind_FINDING_KIND_STALE_SUSPENSE FindingKind = 5
)

// Enum value maps for FindingKind.
var (
	FindingKind_name = map[int32]string{
		0: "FINDING_KIND_UNSPECIFIED",
		1: "FINDING_KIND_BALANCE_DRIFT",
		2: "FINDING_KIND_MISSING_IN_LEDGER",
		3: "FINDING_KIND_MISSING_AT_PROVIDER",
		4: "FINDING_KIND_AMOUNT_MISMATCH",
		5: "FINDING_KIND_STALE_SUSPENSE",
	}
	FindingKind_value = map[string]int32{
		"FINDING_KIND_UNSPECIFIED":         0,
		"FINDING_KIND_BALANCE_DRIFT":       1,
		"FINDING_KIND_MISSING_IN_LEDGER":   2,
		"FINDING_KIND_MISSING_AT_PROVIDER": 3,
		"FINDING_KIND_AMOUNT_MISMATCH":     4,
		"FINDING_KIND_STALE_SUSPENSE":      5,
	}
)

func (x FindingKind) Enum() *FindingKind {
	p := new(FindingKind)
	*p = x
	return p
}

func (x FindingKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FindingKind) Descriptor() protoreflect.EnumDescriptor {
	return file_aibank_core_v1_core_proto_enumTypes[5].Descriptor()
}

func (FindingKind) Type() protoreflect.EnumType {
	return &file_aibank_core_v1_core_proto_enumTypes[5]
}

func (x FindingKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FindingKind.Descriptor instead.
func (FindingKind) EnumDescriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{5}
}

// Estado de una autorización tal como se le reporta a quien consulta.
//
// `EXPIRED` no es un estado almacenado sino uno derivado: es lo que significa una
// retención viva cuya fecha ya pasó. Guardarlo obligaría a escribir en la base
// cada vez que el reloj avanza.
type AuthorizationStatus int32

const (
	AuthorizationStatus_AUTHORIZATION_STATUS_UNSPECIFIED AuthorizationStatus = 0
	// Dinero retenido, todavía no entregado al receptor.
	AuthorizationStatus_AUTHORIZATION_STATUS_AUTHORIZED AuthorizationStatus = 1
	// Liquidada: el dinero está en la cuenta del receptor.
	AuthorizationStatus_AUTHORIZATION_STATUS_CAPTURED           AuthorizationStatus = 2
	AuthorizationStatus_AUTHORIZATION_STATUS_PARTIALLY_REFUNDED AuthorizationStatus = 3
	AuthorizationStatus_AUTHORIZATION_STATUS_REFUNDED           AuthorizationStatus = 4
	// La retención se devolvió al pagador sin cobrar.
	AuthorizationStatus_AUTHORIZATION_STATUS_RELEASED AuthorizationStatus = 5
	// Vigencia terminada y todavía sin barrer. No se puede capturar.
	AuthorizationStatus_AUTHORIZATION_STATUS_EXPIRED AuthorizationStatus = 6
)

// Enum value maps for AuthorizationStatus.
var (
	AuthorizationStatus_name = map[int32]string{
		0: "AUTHORIZATION_STATUS_UNSPECIFIED",
		1: "AUTHORIZATION_STATUS_AUTHORIZED",
		2: "AUTHORIZATION_STATUS_CAPTURED",
		3: "AUTHORIZATION_STATUS_PARTIALLY_REFUNDED",
		4: "AUTHORIZATION_STATUS_REFUNDED",
		5: "AUTHORIZATION_STATUS_RELEASED",
		6: "AUTHORIZATION_STATUS_EXPIRED",
	}
	AuthorizationStatus_value = map[string]int32{
		"AUTHORIZATION_STATUS_UNSPECIFIED":        0,
		"AUTHORIZATION_STATUS_AUTHORIZED":         1,
		"AUTHORIZATION_STATUS_CAPTURED":           2,
		"AUTHORIZATION_STATUS_PARTIALLY_REFUNDED": 3,
		"AUTHORIZATION_STATUS_REFUNDED":           4,
		"AUTHORIZATION_STATUS_RELEASED":           5,
		"AUTHORIZATION_STATUS_EXPIRED":            6,
	}
)

func (x AuthorizationStatus) Enum() *AuthorizationStatus {
	p := new(AuthorizationStatus)
	*p = x
	return p
}

func (x AuthorizationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthorizationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_aibank_core_v1_core_proto_enumTypes[6].Descriptor()
}

func (AuthorizationStatus) Type() protoreflect.EnumType {
	return &file_aibank_core_v1_core_proto_enumTypes[6]
}

func (x AuthorizationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthorizationStatus.Descriptor instead.
func (AuthorizationStatus) EnumDescriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{6}
}

// Motivo de un rechazo sobre una autorización. Viaja en `x-aibank-reason`.
type AuthorizationErrorReason int32

const (
	AuthorizationErrorReason_AUTHORIZATION_ERROR_REASON_UNSPECIFIED          AuthorizationErrorReason = 0
	AuthorizationErrorReason_AUTHORIZATION_ERROR_REASON_INVALID              AuthorizationErrorReason = 1
	AuthorizationErrorReason_AUTHORIZATION_ERROR_REASON_IDEMPOTENCY_CONFLICT AuthorizationErrorReason = 2
	AuthorizationErrorReason_AUTHORIZATION_ERROR_REASON_NOT_FOUND            AuthorizationErrorReason = 3
	AuthorizationErrorReason_AUTHORIZATION_ERROR_REASON_ACCOUNT_NOT_FOUND    AuthorizationErrorReason = 4
	// La cuenta existe pero está congelada o cerrada.
	AuthorizationErrorReason_AUTHORIZATION_ERROR_REASON_ACCOUNT_NOT_OPERATIVE AuthorizationErrorReason = 5
	AuthorizationErrorReason_AUTHORIZATION_ERROR_REASON_EXPIRED               AuthorizationErrorReason = 6
	// La operación no aplica al estado actual (reembolsar sin capturar, por ejemplo).
	AuthorizationErrorReason_AUTHORIZATION_ERROR_REASON_INVALID_STATE      AuthorizationErrorReason = 7
	AuthorizationErrorReason_AUTHORIZATION_ERROR_REASON_INSUFFICIENT_FUNDS AuthorizationErrorReason = 8
	AuthorizationErrorReason_AUTHORIZATION_ERROR_REASON_CURRENCY_MISMATCH  AuthorizationErrorReason = 9
)

// Enum value maps for AuthorizationErrorReason.
var (
	AuthorizationErrorReason_name = map[int32]string{
		0: "AUTHORIZATION_ERROR_REASON_UNSPECIFIED",
		1: "AUTHORIZATION_ERROR_REASON_INVALID",
		2: "AUTHORIZATION_ERROR_REASON_IDEMPOTENCY_CONFLICT",
		3: "AUTHORIZATION_ERROR_REASON_NOT_FOUND",
		4: "AUTHORIZATION_ERROR_REASON_ACCOUNT_NOT_FOUND",
		5: "AUTHORIZATION_ERROR_REASON_ACCOUNT_NOT_OPERATIVE",
		6: "AUTHORIZATION_ERROR_REASON_EXPIRED",
		7: "AUTHORIZATION_ERROR_REASON_INVALID_STATE",
		8: "AUTHORIZATION_ERROR_REASON_INSUFFICIENT_FUNDS",
		9: "AUTHORIZATION_ERROR_REASON_CURRENCY_MISMATCH",
	}
	AuthorizationErrorReason_value = map[string]int32{
		"AUTHORIZATION_ERROR_REASON_UNSPECIFIED":           0,
		"AUTHORIZATION_ERROR_REASON_INVALID":               1,
		"AUTHORIZATION_ERROR_REASON_IDEMPOTENCY_CONFLICT":  2,
		"AUTHORIZATION_ERROR_REASON_NOT_FOUND":             3,
		"AUTHORIZATION_ERROR_REASON_ACCOUNT_NOT_FOUND":     4,
		"AUTHORIZATION_ERROR_REASON_ACCOUNT_NOT_OPERATIVE": 5,
		"AUTHORIZATION_ERROR_REASON_EXPIRED":               6,
		"AUTHORIZATION_ERROR_REASON_INVALID_STATE":         7,
		"AUTHORIZATION_ERROR_REASON_INSUFFICIENT_FUNDS":    8,
		"AUTHORIZATION_ERROR_REASON_CURRENCY_MISMATCH":     9,
	}
)

func (x AuthorizationErrorReason) Enum() *AuthorizationErrorReason {
	p := new(AuthorizationErrorReason)
	*p = x
	return p
}

func (x AuthorizationErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthorizationErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_aibank_core_v1_core_proto_enumTypes[7].Descriptor()
}

func (AuthorizationErrorReason) Type() protoreflect.EnumType {
	return &file_aibank_core_v1_core_proto_enumTypes[7]
}

func (x AuthorizationErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthorizationErrorReason.Descriptor instead.
func (AuthorizationErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{7}
}

// Importe monetario en MICRAS: millonésimas (10^-6) de la unidad mayor.
// 1 USD = 1_000_000; 1 centavo = 10_000; $0,001 = 1_000.
//
// La escala es 6 y no 2 porque el banco liquida pagos entre agentes de software,
// donde un precio de $0,001 por llamada es lo normal: en centavos ese importe no
// existe. La app le sigue mostrando dos decimales a una persona — la escala es de
// almacenamiento, no de presentación.
//
// `amount_micros` es siempre positivo en los asientos: el signo lo aporta la
// dirección contable.
type Money struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AmountMicros  int64                  `protobuf:"varint,1,opt,name=amount_micros,json=amountMicros,proto3" json:"amount_micros,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"` // ISO-4217, 3 letras
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{0}
}

func (x *Money) GetAmountMicros() int64 {
	if x != nil {
		return x.AmountMicros
	}
	return 0
}

func (x *Money) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"` // UUID
	Direction     Direction              `protobuf:"varint,2,opt,name=direction,proto3,enum=aibank.core.v1.Direction" json:"direction,omitempty"`
	Amount        *Money                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{1}
}

func (x *Entry) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Entry) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNSPECIFIED
}

func (x *Entry) GetAmount() *Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

type PostRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Definida por quien origina la operación. Garantiza efecto único.
	IdempotencyKey string `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Naturaleza del movimiento: "deposit", "withdrawal", "p2p_transfer", ...
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// Dos o más asientos que deben balancear por moneda.
	Entries       []*Entry `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	Description   string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostRequest) Reset() {
	*x = PostRequest{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostRequest) ProtoMessage() {}

func (x *PostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostRequest.ProtoReflect.Descriptor instead.
func (*PostRequest) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{2}
}

func (x *PostRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *PostRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PostRequest) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *PostRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	PostedAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=posted_at,json=postedAt,proto3" json:"posted_at,omitempty"`
	// true si la clave ya existía: se devolvió la transacción original sin duplicar.
	Replayed      bool `protobuf:"varint,3,opt,name=replayed,proto3" json:"replayed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostResponse) Reset() {
	*x = PostResponse{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostResponse) ProtoMessage() {}

func (x *PostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostResponse.ProtoReflect.Descriptor instead.
func (*PostResponse) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{3}
}

func (x *PostResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *PostResponse) GetPostedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PostedAt
	}
	return nil
}

func (x *PostResponse) GetReplayed() bool {
	if x != nil {
		return x.Replayed
	}
	return false
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{4}
}

func (x *GetBalanceRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetBalanceResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Balance    *Money                 `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	EntryCount int64                  `protobuf:"varint,2,opt,name=entry_count,json=entryCount,proto3" json:"entry_count,omitempty"`
	// Saldo recalculado desde los asientos. Debe coincidir con `balance`;
	// una discrepancia es un incidente contable.
	ProjectedBalance *Money `protobuf:"bytes,3,opt,name=projected_balance,json=projectedBalance,proto3" json:"projected_balance,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{5}
}

func (x *GetBalanceResponse) GetBalance() *Money {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *GetBalanceResponse) GetEntryCount() int64 {
	if x != nil {
		return x.EntryCount
	}
	return 0
}

func (x *GetBalanceResponse) GetProjectedBalance() *Money {
	if x != nil {
		return x.ProjectedBalance
	}
	return nil
}

// Movimiento tal como se muestra en un extracto.
type AccountEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identidad estable para paginar. Opaca para el cliente.
	Cursor        string    `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	TransactionId string    `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Direction     Direction `protobuf:"varint,3,opt,name=direction,proto3,enum=aibank.core.v1.Direction" json:"direction,omitempty"`
	Amount        *Money    `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// "deposit", "p2p_transfer", "rail_inbound_credit", ...
	Kind          string                 `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	PostedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=posted_at,json=postedAt,proto3" json:"posted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountEntry) Reset() {
	*x = AccountEntry{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountEntry) ProtoMessage() {}

func (x *AccountEntry) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountEntry.ProtoReflect.Descriptor instead.
func (*AccountEntry) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{6}
}

func (x *AccountEntry) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *AccountEntry) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *AccountEntry) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNSPECIFIED
}

func (x *AccountEntry) GetAmount() *Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *AccountEntry) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AccountEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AccountEntry) GetPostedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PostedAt
	}
	return nil
}

type ListEntriesRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AccountId string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Máximo de movimientos a devolver. 0 = valor por defecto del servidor.
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Cursor de la página anterior; vacío para empezar por el movimiento más reciente.
	Cursor        string `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntriesRequest) Reset() {
	*x = ListEntriesRequest{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesRequest) ProtoMessage() {}

func (x *ListEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesRequest.ProtoReflect.Descriptor instead.
func (*ListEntriesRequest) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{7}
}

func (x *ListEntriesRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ListEntriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListEntriesRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListEntriesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Del más reciente al más antiguo.
	Entries []*AccountEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	// Vacío cuando no hay más páginas.
	NextCursor    string `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntriesResponse) Reset() {
	*x = ListEntriesResponse{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesResponse) ProtoMessage() {}

func (x *ListEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesResponse.ProtoReflect.Descriptor instead.
func (*ListEntriesResponse) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{8}
}

func (x *ListEntriesResponse) GetEntries() []*AccountEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListEntriesResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type Account struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code            string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type            AccountType            `protobuf:"varint,4,opt,name=type,proto3,enum=aibank.core.v1.AccountType" json:"type,omitempty"`
	Owner           AccountOwner           `protobuf:"varint,5,opt,name=owner,proto3,enum=aibank.core.v1.AccountOwner" json:"owner,omitempty"`
	OwnerId         string                 `protobuf:"bytes,6,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`       // vacío en cuentas internas
	ProductId       string                 `protobuf:"bytes,7,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"` // vacío en cuentas internas
	Currency        string                 `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	Status          AccountStatus          `protobuf:"varint,9,opt,name=status,proto3,enum=aibank.core.v1.AccountStatus" json:"status,omitempty"`
	AllowsOverdraft bool                   `protobuf:"varint,10,opt,name=allows_overdraft,json=allowsOverdraft,proto3" json:"allows_overdraft,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{9}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetType() AccountType {
	if x != nil {
		return x.Type
	}
	return AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *Account) GetOwner() AccountOwner {
	if x != nil {
		return x.Owner
	}
	return AccountOwner_ACCOUNT_OWNER_UNSPECIFIED
}

func (x *Account) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Account) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Account) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Account) GetStatus() AccountStatus {
	if x != nil {
		return x.Status
	}
	return AccountStatus_ACCOUNT_STATUS_UNSPECIFIED
}

func (x *Account) GetAllowsOverdraft() bool {
	if x != nil {
		return x.AllowsOverdraft
	}
	return false
}

func (x *Account) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type OpenCustomerAccountRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Code       string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name       string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CustomerId string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Producto del catálogo del que la cuenta hereda moneda y reglas.
	ProductCode   string `protobuf:"bytes,4,opt,name=product_code,json=productCode,proto3" json:"product_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenCustomerAccountRequest) Reset() {
	*x = OpenCustomerAccountRequest{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenCustomerAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenCustomerAccountRequest) ProtoMessage() {}

func (x *OpenCustomerAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenCustomerAccountRequest.ProtoReflect.Descriptor instead.
func (*OpenCustomerAccountRequest) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{10}
}

func (x *OpenCustomerAccountRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *OpenCustomerAccountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OpenCustomerAccountRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *OpenCustomerAccountRequest) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

type CreateInternalAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          AccountType            `protobuf:"varint,3,opt,name=type,proto3,enum=aibank.core.v1.AccountType" json:"type,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInternalAccountRequest) Reset() {
	*x = CreateInternalAccountRequest{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInternalAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInternalAccountRequest) ProtoMessage() {}

func (x *CreateInternalAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInternalAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateInternalAccountRequest) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{11}
}

func (x *CreateInternalAccountRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateInternalAccountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateInternalAccountRequest) GetType() AccountType {
	if x != nil {
		return x.Type
	}
	return AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *CreateInternalAccountRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{12}
}

func (x *GetAccountRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetAccountByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountByIdRequest) Reset() {
	*x = GetAccountByIdRequest{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountByIdRequest) ProtoMessage() {}

func (x *GetAccountByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountByIdRequest.ProtoReflect.Descriptor instead.
func (*GetAccountByIdRequest) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{13}
}

func (x *GetAccountByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Product struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code            string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Currency        string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	AllowsOverdraft bool                   `protobuf:"varint,5,opt,name=allows_overdraft,json=allowsOverdraft,proto3" json:"allows_overdraft,omitempty"`
	// Topes regulatorios; ausentes = sin tope.
	MaxBalanceMicros     *int64 `protobuf:"varint,6,opt,name=max_balance_micros,json=maxBalanceMicros,proto3,oneof" json:"max_balance_micros,omitempty"`
	MaxTransactionMicros *int64 `protobuf:"varint,7,opt,name=max_transaction_micros,json=maxTransactionMicros,proto3,oneof" json:"max_transaction_micros,omitempty"`
	Active               bool   `protobuf:"varint,8,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{14}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Product) GetAllowsOverdraft() bool {
	if x != nil {
		return x.AllowsOverdraft
	}
	return false
}

func (x *Product) GetMaxBalanceMicros() int64 {
	if x != nil && x.MaxBalanceMicros != nil {
		return *x.MaxBalanceMicros
	}
	return 0
}

func (x *Product) GetMaxTransactionMicros() int64 {
	if x != nil && x.MaxTransactionMicros != nil {
		return *x.MaxTransactionMicros
	}
	return 0
}

func (x *Product) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type CreateProductRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Code                 string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Currency             string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	AllowsOverdraft      bool                   `protobuf:"varint,4,opt,name=allows_overdraft,json=allowsOverdraft,proto3" json:"allows_overdraft,omitempty"`
	MaxBalanceMicros     *int64                 `protobuf:"varint,5,opt,name=max_balance_micros,json=maxBalanceMicros,proto3,oneof" json:"max_balance_micros,omitempty"`
	MaxTransactionMicros *int64                 `protobuf:"varint,6,opt,name=max_transaction_micros,json=maxTransactionMicros,proto3,oneof" json:"max_transaction_micros,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{15}
}

func (x *CreateProductRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateProductRequest) GetAllowsOverdraft() bool {
	if x != nil {
		return x.AllowsOverdraft
	}
	return false
}

func (x *CreateProductRequest) GetMaxBalanceMicros() int64 {
	if x != nil && x.MaxBalanceMicros != nil {
		return *x.MaxBalanceMicros
	}
	return 0
}

func (x *CreateProductRequest) GetMaxTransactionMicros() int64 {
	if x != nil && x.MaxTransactionMicros != nil {
		return *x.MaxTransactionMicros
	}
	return 0
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{16}
}

func (x *GetProductRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type Finding struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RunId     string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Kind      FindingKind            `protobuf:"varint,3,opt,name=kind,proto3,enum=aibank.core.v1.FindingKind" json:"kind,omitempty"`
	AccountId string                 `protobuf:"bytes,4,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Reference string                 `protobuf:"bytes,5,opt,name=reference,proto3" json:"reference,omitempty"`
	// Lo que debería ser y lo que hay, en micras.
	ExpectedMicros int64                  `protobuf:"varint,6,opt,name=expected_micros,json=expectedMicros,proto3" json:"expected_micros,omitempty"`
	ActualMicros   int64                  `protobuf:"varint,7,opt,name=actual_micros,json=actualMicros,proto3" json:"actual_micros,omitempty"`
	Currency       string                 `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	Detail         string                 `protobuf:"bytes,9,opt,name=detail,proto3" json:"detail,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{17}
}

func (x *Finding) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Finding) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Finding) GetKind() FindingKind {
	if x != nil {
		return x.Kind
	}
	return FindingKind_FINDING_KIND_UNSPECIFIED
}

func (x *Finding) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Finding) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *Finding) GetExpectedMicros() int64 {
	if x != nil {
		return x.ExpectedMicros
	}
	return 0
}

func (x *Finding) GetActualMicros() int64 {
	if x != nil {
		return x.ActualMicros
	}
	return 0
}

func (x *Finding) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Finding) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *Finding) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListOpenFindingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOpenFindingsRequest) Reset() {
	*x = ListOpenFindingsRequest{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOpenFindingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOpenFindingsRequest) ProtoMessage() {}

func (x *ListOpenFindingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOpenFindingsRequest.ProtoReflect.Descriptor instead.
func (*ListOpenFindingsRequest) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{18}
}

func (x *ListOpenFindingsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListOpenFindingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Findings      []*Finding             `protobuf:"bytes,1,rep,name=findings,proto3" json:"findings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOpenFindingsResponse) Reset() {
	*x = ListOpenFindingsResponse{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOpenFindingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOpenFindingsResponse) ProtoMessage() {}

func (x *ListOpenFindingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOpenFindingsResponse.ProtoReflect.Descriptor instead.
func (*ListOpenFindingsResponse) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{19}
}

func (x *ListOpenFindingsResponse) GetFindings() []*Finding {
	if x != nil {
		return x.Findings
	}
	return nil
}

type ResolveFindingRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	FindingId int64                  `protobuf:"varint,1,opt,name=finding_id,json=findingId,proto3" json:"finding_id,omitempty"`
	// Cómo se resolvió. Queda registrado: una diferencia cerrada sin explicación
	// no sirve ante una auditoría.
	Resolution    string `protobuf:"bytes,2,opt,name=resolution,proto3" json:"resolution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveFindingRequest) Reset() {
	*x = ResolveFindingRequest{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveFindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveFindingRequest) ProtoMessage() {}

func (x *ResolveFindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveFindingRequest.ProtoReflect.Descriptor instead.
func (*ResolveFindingRequest) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{20}
}

func (x *ResolveFindingRequest) GetFindingId() int64 {
	if x != nil {
		return x.FindingId
	}
	return 0
}

func (x *ResolveFindingRequest) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

type ResolveFindingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resolved      bool                   `protobuf:"varint,1,opt,name=resolved,proto3" json:"resolved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveFindingResponse) Reset() {
	*x = ResolveFindingResponse{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveFindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveFindingResponse) ProtoMessage() {}

func (x *ResolveFindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveFindingResponse.ProtoReflect.Descriptor instead.
func (*ResolveFindingResponse) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{21}
}

func (x *ResolveFindingResponse) GetResolved() bool {
	if x != nil {
		return x.Resolved
	}
	return false
}

type RunInternalCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunInternalCheckRequest) Reset() {
	*x = RunInternalCheckRequest{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunInternalCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunInternalCheckRequest) ProtoMessage() {}

func (x *RunInternalCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunInternalCheckRequest.ProtoReflect.Descriptor instead.
func (*RunInternalCheckRequest) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{22}
}

type RunInternalCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	FindingsCount int32                  `protobuf:"varint,2,opt,name=findings_count,json=findingsCount,proto3" json:"findings_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunInternalCheckResponse) Reset() {
	*x = RunInternalCheckResponse{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunInternalCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunInternalCheckResponse) ProtoMessage() {}

func (x *RunInternalCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunInternalCheckResponse.ProtoReflect.Descriptor instead.
func (*RunInternalCheckResponse) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{23}
}

func (x *RunInternalCheckResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunInternalCheckResponse) GetFindingsCount() int32 {
	if x != nil {
		return x.FindingsCount
	}
	return 0
}

type Authorization struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	PayerAccountId string                 `protobuf:"bytes,3,opt,name=payer_account_id,json=payerAccountId,proto3" json:"payer_account_id,omitempty"`
	PayeeAccountId string                 `protobuf:"bytes,4,opt,name=payee_account_id,json=payeeAccountId,proto3" json:"payee_account_id,omitempty"`
	Amount         *Money                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Status         AuthorizationStatus    `protobuf:"varint,6,opt,name=status,proto3,enum=aibank.core.v1.AuthorizationStatus" json:"status,omitempty"`
	// Cuánto se devolvió ya. Cero mientras no haya reembolso.
	RefundedMicros int64                  `protobuf:"varint,7,opt,name=refunded_micros,json=refundedMicros,proto3" json:"refunded_micros,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Presente solo si se capturó.
	SettledAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=settled_at,json=settledAt,proto3,oneof" json:"settled_at,omitempty"`
	ReleasedAt    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=released_at,json=releasedAt,proto3,oneof" json:"released_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authorization) Reset() {
	*x = Authorization{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authorization) ProtoMessage() {}

func (x *Authorization) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authorization.ProtoReflect.Descriptor instead.
func (*Authorization) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{24}
}

func (x *Authorization) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Authorization) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Authorization) GetPayerAccountId() string {
	if x != nil {
		return x.PayerAccountId
	}
	return ""
}

func (x *Authorization) GetPayeeAccountId() string {
	if x != nil {
		return x.PayeeAccountId
	}
	return ""
}

func (x *Authorization) GetAmount() *Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Authorization) GetStatus() AuthorizationStatus {
	if x != nil {
		return x.Status
	}
	return AuthorizationStatus_AUTHORIZATION_STATUS_UNSPECIFIED
}

func (x *Authorization) GetRefundedMicros() int64 {
	if x != nil {
		return x.RefundedMicros
	}
	return 0
}

func (x *Authorization) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Authorization) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Authorization) GetSettledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SettledAt
	}
	return nil
}

func (x *Authorization) GetReleasedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReleasedAt
	}
	return nil
}

type AuthorizeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	PayerAccountId string                 `protobuf:"bytes,2,opt,name=payer_account_id,json=payerAccountId,proto3" json:"payer_account_id,omitempty"`
	PayeeAccountId string                 `protobuf:"bytes,3,opt,name=payee_account_id,json=payeeAccountId,proto3" json:"payee_account_id,omitempty"`
	Amount         *Money                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// Vigencia. 0 = valor por defecto del servidor (15 minutos).
	TtlMinutes    int32 `protobuf:"varint,5,opt,name=ttl_minutes,json=ttlMinutes,proto3" json:"ttl_minutes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{25}
}

func (x *AuthorizeRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *AuthorizeRequest) GetPayerAccountId() string {
	if x != nil {
		return x.PayerAccountId
	}
	return ""
}

func (x *AuthorizeRequest) GetPayeeAccountId() string {
	if x != nil {
		return x.PayeeAccountId
	}
	return ""
}

func (x *AuthorizeRequest) GetAmount() *Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *AuthorizeRequest) GetTtlMinutes() int32 {
	if x != nil {
		return x.TtlMinutes
	}
	return 0
}

type AuthorizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authorization *Authorization         `protobuf:"bytes,1,opt,name=authorization,proto3" json:"authorization,omitempty"`
	// true si la clave ya existía y se devolvió la autorización original.
	Replayed      bool `protobuf:"varint,2,opt,name=replayed,proto3" json:"replayed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{26}
}

func (x *AuthorizeResponse) GetAuthorization() *Authorization {
	if x != nil {
		return x.Authorization
	}
	return nil
}

func (x *AuthorizeResponse) GetReplayed() bool {
	if x != nil {
		return x.Replayed
	}
	return false
}

type CaptureRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AuthorizationId string                 `protobuf:"bytes,1,opt,name=authorization_id,json=authorizationId,proto3" json:"authorization_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CaptureRequest) Reset() {
	*x = CaptureRequest{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureRequest) ProtoMessage() {}

func (x *CaptureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureRequest.ProtoReflect.Descriptor instead.
func (*CaptureRequest) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{27}
}

func (x *CaptureRequest) GetAuthorizationId() string {
	if x != nil {
		return x.AuthorizationId
	}
	return ""
}

type RefundRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AuthorizationId string                 `protobuf:"bytes,1,opt,name=authorization_id,json=authorizationId,proto3" json:"authorization_id,omitempty"`
	// 0 = reembolso total de lo que quede sin devolver.
	AmountMicros  int64 `protobuf:"varint,2,opt,name=amount_micros,json=amountMicros,proto3" json:"amount_micros,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundRequest) Reset() {
	*x = RefundRequest{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundRequest) ProtoMessage() {}

func (x *RefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundRequest.ProtoReflect.Descriptor instead.
func (*RefundRequest) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{28}
}

func (x *RefundRequest) GetAuthorizationId() string {
	if x != nil {
		return x.AuthorizationId
	}
	return ""
}

func (x *RefundRequest) GetAmountMicros() int64 {
	if x != nil {
		return x.AmountMicros
	}
	return 0
}

type GetAuthorizationRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AuthorizationId string                 `protobuf:"bytes,1,opt,name=authorization_id,json=authorizationId,proto3" json:"authorization_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetAuthorizationRequest) Reset() {
	*x = GetAuthorizationRequest{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorizationRequest) ProtoMessage() {}

func (x *GetAuthorizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorizationRequest.ProtoReflect.Descriptor instead.
func (*GetAuthorizationRequest) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{29}
}

func (x *GetAuthorizationRequest) GetAuthorizationId() string {
	if x != nil {
		return x.AuthorizationId
	}
	return ""
}

type ReleaseExpiredRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Máximo de autorizaciones a liberar en esta pasada. 0 = valor por defecto.
	Limit         int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseExpiredRequest) Reset() {
	*x = ReleaseExpiredRequest{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseExpiredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseExpiredRequest) ProtoMessage() {}

func (x *ReleaseExpiredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseExpiredRequest.ProtoReflect.Descriptor instead.
func (*ReleaseExpiredRequest) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{30}
}

func (x *ReleaseExpiredRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ReleaseExpiredResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AuthorizationIds []string               `protobuf:"bytes,1,rep,name=authorization_ids,json=authorizationIds,proto3" json:"authorization_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReleaseExpiredResponse) Reset() {
	*x = ReleaseExpiredResponse{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseExpiredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseExpiredResponse) ProtoMessage() {}

func (x *ReleaseExpiredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseExpiredResponse.ProtoReflect.Descriptor instead.
func (*ReleaseExpiredResponse) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{31}
}

func (x *ReleaseExpiredResponse) GetAuthorizationIds() []string {
	if x != nil {
		return x.AuthorizationIds
	}
	return nil
}

var File_aibank_core_v1_core_proto protoreflect.FileDescriptor

const file_aibank_core_v1_core_proto_rawDesc = "" +
	"\n" +
	"\x19aibank/core/v1/core.proto\x12\x0eaibank.core.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"H\n" +
	"\x05Money\x12#\n" +
	"\ramount_micros\x18\x01 \x01(\x03R\famountMicros\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"\x8e\x01\n" +
	"\x05Entry\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x127\n" +
	"\tdirection\x18\x02 \x01(\x0e2\x19.aibank.core.v1.DirectionR\tdirection\x12-\n" +
	"\x06amount\x18\x03 \x01(\v2\x15.aibank.core.v1.MoneyR\x06amount\"\x9d\x01\n" +
	"\vPostRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12/\n" +
	"\aentries\x18\x03 \x03(\v2\x15.aibank.core.v1.EntryR\aentries\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\x8a\x01\n" +
	"\fPostResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x127\n" +
	"\tposted_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bpostedAt\x12\x1a\n" +
	"\breplayed\x18\x03 \x01(\bR\breplayed\"2\n" +
	"\x11GetBalanceRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"\xaa\x01\n" +
	"\x12GetBalanceResponse\x12/\n" +
	"\abalance\x18\x01 \x01(\v2\x15.aibank.core.v1.MoneyR\abalance\x12\x1f\n" +
	"\ventry_count\x18\x02 \x01(\x03R\n" +
	"entryCount\x12B\n" +
	"\x11projected_balance\x18\x03 \x01(\v2\x15.aibank.core.v1.MoneyR\x10projectedBalance\"\xa4\x02\n" +
	"\fAccountEntry\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x127\n" +
	"\tdirection\x18\x03 \x01(\x0e2\x19.aibank.core.v1.DirectionR\tdirection\x12-\n" +
	"\x06amount\x18\x04 \x01(\v2\x15.aibank.core.v1.MoneyR\x06amount\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x127\n" +
	"\tposted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bpostedAt\"a\n" +
	"\x12ListEntriesRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\"n\n" +
	"\x13ListEntriesResponse\x126\n" +
	"\aentries\x18\x01 \x03(\v2\x1c.aibank.core.v1.AccountEntryR\aentries\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"\x99\x03\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12/\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1b.aibank.core.v1.AccountTypeR\x04type\x122\n" +
	"\x05owner\x18\x05 \x01(\x0e2\x1c.aibank.core.v1.AccountOwnerR\x05owner\x12\x19\n" +
	"\bowner_id\x18\x06 \x01(\tR\aownerId\x12\x1d\n" +
	"\n" +
	"product_id\x18\a \x01(\tR\tproductId\x12\x1a\n" +
	"\bcurrency\x18\b \x01(\tR\bcurrency\x125\n" +
	"\x06status\x18\t \x01(\x0e2\x1d.aibank.core.v1.AccountStatusR\x06status\x12)\n" +
	"\x10allows_overdraft\x18\n" +
	" \x01(\bR\x0fallowsOverdraft\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x88\x01\n" +
	"\x1aOpenCustomerAccountRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12!\n" +
	"\fproduct_code\x18\x04 \x01(\tR\vproductCode\"\x93\x01\n" +
	"\x1cCreateInternalAccountRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12/\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1b.aibank.core.v1.AccountTypeR\x04type\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"'\n" +
	"\x11GetAccountRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"'\n" +
	"\x15GetAccountByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc0\x02\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12)\n" +
	"\x10allows_overdraft\x18\x05 \x01(\bR\x0fallowsOverdraft\x121\n" +
	"\x12max_balance_micros\x18\x06 \x01(\x03H\x00R\x10maxBalanceMicros\x88\x01\x01\x129\n" +
	"\x16max_transaction_micros\x18\a \x01(\x03H\x01R\x14maxTransactionMicros\x88\x01\x01\x12\x16\n" +
	"\x06active\x18\b \x01(\bR\x06activeB\x15\n" +
	"\x13_max_balance_microsB\x19\n" +
	"\x17_max_transaction_micros\"\xa5\x02\n" +
	"\x14CreateProductRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12)\n" +
	"\x10allows_overdraft\x18\x04 \x01(\bR\x0fallowsOverdraft\x121\n" +
	"\x12max_balance_micros\x18\x05 \x01(\x03H\x00R\x10maxBalanceMicros\x88\x01\x01\x129\n" +
	"\x16max_transaction_micros\x18\x06 \x01(\x03H\x01R\x14maxTransactionMicros\x88\x01\x01B\x15\n" +
	"\x13_max_balance_microsB\x19\n" +
	"\x17_max_transaction_micros\"'\n" +
	"\x11GetProductRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\xdb\x02\n" +
	"\aFinding\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12/\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x1b.aibank.core.v1.FindingKindR\x04kind\x12\x1d\n" +
	"\n" +
	"account_id\x18\x04 \x01(\tR\taccountId\x12\x1c\n" +
	"\treference\x18\x05 \x01(\tR\treference\x12'\n" +
	"\x0fexpected_micros\x18\x06 \x01(\x03R\x0eexpectedMicros\x12#\n" +
	"\ractual_micros\x18\a \x01(\x03R\factualMicros\x12\x1a\n" +
	"\bcurrency\x18\b \x01(\tR\bcurrency\x12\x16\n" +
	"\x06detail\x18\t \x01(\tR\x06detail\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"/\n" +
	"\x17ListOpenFindingsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"O\n" +
	"\x18ListOpenFindingsResponse\x123\n" +
	"\bfindings\x18\x01 \x03(\v2\x17.aibank.core.v1.FindingR\bfindings\"V\n" +
	"\x15ResolveFindingRequest\x12\x1d\n" +
	"\n" +
	"finding_id\x18\x01 \x01(\x03R\tfindingId\x12\x1e\n" +
	"\n" +
	"resolution\x18\x02 \x01(\tR\n" +
	"resolution\"4\n" +
	"\x16ResolveFindingResponse\x12\x1a\n" +
	"\bresolved\x18\x01 \x01(\bR\bresolved\"\x19\n" +
	"\x17RunInternalCheckRequest\"X\n" +
	"\x18RunInternalCheckResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12%\n" +
	"\x0efindings_count\x18\x02 \x01(\x05R\rfindingsCount\"\xc8\x04\n" +
	"\rAuthorization\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12(\n" +
	"\x10payer_account_id\x18\x03 \x01(\tR\x0epayerAccountId\x12(\n" +
	"\x10payee_account_id\x18\x04 \x01(\tR\x0epayeeAccountId\x12-\n" +
	"\x06amount\x18\x05 \x01(\v2\x15.aibank.core.v1.MoneyR\x06amount\x12;\n" +
	"\x06status\x18\x06 \x01(\x0e2#.aibank.core.v1.AuthorizationStatusR\x06status\x12'\n" +
	"\x0frefunded_micros\x18\a \x01(\x03R\x0erefundedMicros\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12>\n" +
	"\n" +
	"settled_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tsettledAt\x88\x01\x01\x12@\n" +
	"\vreleased_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampH\x01R\n" +
	"releasedAt\x88\x01\x01B\r\n" +
	"\v_settled_atB\x0e\n" +
	"\f_released_at\"\xdf\x01\n" +
	"\x10AuthorizeRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12(\n" +
	"\x10payer_account_id\x18\x02 \x01(\tR\x0epayerAccountId\x12(\n" +
	"\x10payee_account_id\x18\x03 \x01(\tR\x0epayeeAccountId\x12-\n" +
	"\x06amount\x18\x04 \x01(\v2\x15.aibank.core.v1.MoneyR\x06amount\x12\x1f\n" +
	"\vttl_minutes\x18\x05 \x01(\x05R\n" +
	"ttlMinutes\"t\n" +
	"\x11AuthorizeResponse\x12C\n" +
	"\rauthorization\x18\x01 \x01(\v2\x1d.aibank.core.v1.AuthorizationR\rauthorization\x12\x1a\n" +
	"\breplayed\x18\x02 \x01(\bR\breplayed\";\n" +
	"\x0eCaptureRequest\x12)\n" +
	"\x10authorization_id\x18\x01 \x01(\tR\x0fauthorizationId\"_\n" +
	"\rRefundRequest\x12)\n" +
	"\x10authorization_id\x18\x01 \x01(\tR\x0fauthorizationId\x12#\n" +
	"\ramount_micros\x18\x02 \x01(\x03R\famountMicros\"D\n" +
	"\x17GetAuthorizationRequest\x12)\n" +
	"\x10authorization_id\x18\x01 \x01(\tR\x0fauthorizationId\"-\n" +
	"\x15ReleaseExpiredRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"E\n" +
	"\x16ReleaseExpiredResponse\x12+\n" +
	"\x11authorization_ids\x18\x01 \x03(\tR\x10authorizationIds*Q\n" +
	"\tDirection\x12\x19\n" +
	"\x15DIRECTION_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fDIRECTION_DEBIT\x10\x01\x12\x14\n" +
	"\x10DIRECTION_CREDIT\x10\x02*\xab\x01\n" +
	"\vAccountType\x12\x1c\n" +
	"\x18ACCOUNT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ACCOUNT_TYPE_ASSET\x10\x01\x12\x1a\n" +
	"\x16ACCOUNT_TYPE_LIABILITY\x10\x02\x12\x17\n" +
	"\x13ACCOUNT_TYPE_EQUITY\x10\x03\x12\x17\n" +
	"\x13ACCOUNT_TYPE_INCOME\x10\x04\x12\x18\n" +
	"\x14ACCOUNT_TYPE_EXPENSE\x10\x05*e\n" +
	"\fAccountOwner\x12\x1d\n" +
	"\x19ACCOUNT_OWNER_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ACCOUNT_OWNER_CUSTOMER\x10\x01\x12\x1a\n" +
	"\x16ACCOUNT_OWNER_INTERNAL\x10\x02*\x80\x01\n" +
	"\rAccountStatus\x12\x1e\n" +
	"\x1aACCOUNT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ACCOUNT_STATUS_ACTIVE\x10\x01\x12\x19\n" +
	"\x15ACCOUNT_STATUS_FROZEN\x10\x02\x12\x19\n" +
	"\x15ACCOUNT_STATUS_CLOSED\x10\x03*\xc3\x02\n" +
	"\x12PostingErrorReason\x12$\n" +
	" POSTING_ERROR_REASON_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cPOSTING_ERROR_REASON_INVALID\x10\x01\x12-\n" +
	")POSTING_ERROR_REASON_IDEMPOTENCY_CONFLICT\x10\x02\x12+\n" +
	"'POSTING_ERROR_REASON_INSUFFICIENT_FUNDS\x10\x03\x12-\n" +
	")POSTING_ERROR_REASON_BALANCE_CAP_EXCEEDED\x10\x04\x121\n" +
	"-POSTING_ERROR_REASON_TRANSACTION_CAP_EXCEEDED\x10\x05\x12'\n" +
	"#POSTING_ERROR_REASON_ALREADY_EXISTS\x10\x06*\xd8\x01\n" +
	"\vFindingKind\x12\x1c\n" +
	"\x18FINDING_KIND_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aFINDING_KIND_BALANCE_DRIFT\x10\x01\x12\"\n" +
	"\x1eFINDING_KIND_MISSING_IN_LEDGER\x10\x02\x12$\n" +
	" FINDING_KIND_MISSING_AT_PROVIDER\x10\x03\x12 \n" +
	"\x1cFINDING_KIND_AMOUNT_MISMATCH\x10\x04\x12\x1f\n" +
	"\x1bFINDING_KIND_STALE_SUSPENSE\x10\x05*\x98\x02\n" +
	"\x13AuthorizationStatus\x12$\n" +
	" AUTHORIZATION_STATUS_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fAUTHORIZATION_STATUS_AUTHORIZED\x10\x01\x12!\n" +
	"\x1dAUTHORIZATION_STATUS_CAPTURED\x10\x02\x12+\n" +
	"'AUTHORIZATION_STATUS_PARTIALLY_REFUNDED\x10\x03\x12!\n" +
	"\x1dAUTHORIZATION_STATUS_REFUNDED\x10\x04\x12!\n" +
	"\x1dAUTHORIZATION_STATUS_RELEASED\x10\x05\x12 \n" +
	"\x1cAUTHORIZATION_STATUS_EXPIRED\x10\x06*\xf0\x03\n" +
	"\x18AuthorizationErrorReason\x12*\n" +
	"&AUTHORIZATION_ERROR_REASON_UNSPECIFIED\x10\x00\x12&\n" +
	"\"AUTHORIZATION_ERROR_REASON_INVALID\x10\x01\x123\n" +
	"/AUTHORIZATION_ERROR_REASON_IDEMPOTENCY_CONFLICT\x10\x02\x12(\n" +
	"$AUTHORIZATION_ERROR_REASON_NOT_FOUND\x10\x03\x120\n" +
	",AUTHORIZATION_ERROR_REASON_ACCOUNT_NOT_FOUND\x10\x04\x124\n" +
	"0AUTHORIZATION_ERROR_REASON_ACCOUNT_NOT_OPERATIVE\x10\x05\x12&\n" +
	"\"AUTHORIZATION_ERROR_REASON_EXPIRED\x10\x06\x12,\n" +
	"(AUTHORIZATION_ERROR_REASON_INVALID_STATE\x10\a\x121\n" +
	"-AUTHORIZATION_ERROR_REASON_INSUFFICIENT_FUNDS\x10\b\x120\n" +
	",AUTHORIZATION_ERROR_REASON_CURRENCY_MISMATCH\x10\t2\xff\x01\n" +
	"\rLedgerService\x12A\n" +
	"\x04Post\x12\x1b.aibank.core.v1.PostRequest\x1a\x1c.aibank.core.v1.PostResponse\x12S\n" +
	"\n" +
	"GetBalance\x12!.aibank.core.v1.GetBalanceRequest\x1a\".aibank.core.v1.GetBalanceResponse\x12V\n" +
	"\vListEntries\x12\".aibank.core.v1.ListEntriesRequest\x1a#.aibank.core.v1.ListEntriesResponse2\xe8\x02\n" +
	"\x0eAccountService\x12Z\n" +
	"\x13OpenCustomerAccount\x12*.aibank.core.v1.OpenCustomerAccountRequest\x1a\x17.aibank.core.v1.Account\x12^\n" +
	"\x15CreateInternalAccount\x12,.aibank.core.v1.CreateInternalAccountRequest\x1a\x17.aibank.core.v1.Account\x12H\n" +
	"\n" +
	"GetAccount\x12!.aibank.core.v1.GetAccountRequest\x1a\x17.aibank.core.v1.Account\x12P\n" +
	"\x0eGetAccountById\x12%.aibank.core.v1.GetAccountByIdRequest\x1a\x17.aibank.core.v1.Account2\xaa\x01\n" +
	"\x0eProductService\x12N\n" +
	"\rCreateProduct\x12$.aibank.core.v1.CreateProductRequest\x1a\x17.aibank.core.v1.Product\x12H\n" +
	"\n" +
	"GetProduct\x12!.aibank.core.v1.GetProductRequest\x1a\x17.aibank.core.v1.Product2\xc6\x02\n" +
	"\x15ReconciliationService\x12e\n" +
	"\x10ListOpenFindings\x12'.aibank.core.v1.ListOpenFindingsRequest\x1a(.aibank.core.v1.ListOpenFindingsResponse\x12_\n" +
	"\x0eResolveFinding\x12%.aibank.core.v1.ResolveFindingRequest\x1a&.aibank.core.v1.ResolveFindingResponse\x12e\n" +
	"\x10RunInternalCheck\x12'.aibank.core.v1.RunInternalCheckRequest\x1a(.aibank.core.v1.RunInternalCheckResponse2\xb7\x03\n" +
	"\x14AuthorizationService\x12P\n" +
	"\tAuthorize\x12 .aibank.core.v1.AuthorizeRequest\x1a!.aibank.core.v1.AuthorizeResponse\x12H\n" +
	"\aCapture\x12\x1e.aibank.core.v1.CaptureRequest\x1a\x1d.aibank.core.v1.Authorization\x12F\n" +
	"\x06Refund\x12\x1d.aibank.core.v1.RefundRequest\x1a\x1d.aibank.core.v1.Authorization\x12Z\n" +
	"\x10GetAuthorization\x12'.aibank.core.v1.GetAuthorizationRequest\x1a\x1d.aibank.core.v1.Authorization\x12_\n" +
	"\x0eReleaseExpired\x12%.aibank.core.v1.ReleaseExpiredRequest\x1a&.aibank.core.v1.ReleaseExpiredResponseB3Z1github.com/aibank/aibank/clients/go/corev1;corev1b\x06proto3"

var (
	file_aibank_core_v1_core_proto_rawDescOnce sync.Once
	file_aibank_core_v1_core_proto_rawDescData []byte
)

func file_aibank_core_v1_core_proto_rawDescGZIP() []byte {
	file_aibank_core_v1_core_proto_rawDescOnce.Do(func() {
		file_aibank_core_v1_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aibank_core_v1_core_proto_rawDesc), len(file_aibank_core_v1_core_proto_rawDesc)))
	})
	return file_aibank_core_v1_core_proto_rawDescData
}

var file_aibank_core_v1_core_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_aibank_core_v1_core_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_aibank_core_v1_core_proto_goTypes = []any{
	(Direction)(0),                       // 0: aibank.core.v1.Direction
	(AccountType)(0),                     // 1: aibank.core.v1.AccountType
	(AccountOwner)(0),                    // 2: aibank.core.v1.AccountOwner
	(AccountStatus)(0),                   // 3: aibank.core.v1.AccountStatus
	(PostingErrorReason)(0),              // 4: aibank.core.v1.PostingErrorReason
	(FindingKind)(0),                     // 5: aibank.core.v1.FindingKind
	(AuthorizationStatus)(0),             // 6: aibank.core.v1.AuthorizationStatus
	(AuthorizationErrorReason)(0),        // 7: aibank.core.v1.AuthorizationErrorReason
	(*Money)(nil),                        // 8: aibank.core.v1.Money
	(*Entry)(nil),                        // 9: aibank.core.v1.Entry
	(*PostRequest)(nil),                  // 10: aibank.core.v1.PostRequest
	(*PostResponse)(nil),                 // 11: aibank.core.v1.PostResponse
	(*GetBalanceRequest)(nil),            // 12: aibank.core.v1.GetBalanceRequest
	(*GetBalanceResponse)(nil),           // 13: aibank.core.v1.GetBalanceResponse
	(*AccountEntry)(nil),                 // 14: aibank.core.v1.AccountEntry
	(*ListEntriesRequest)(nil),           // 15: aibank.core.v1.ListEntriesRequest
	(*ListEntriesResponse)(nil),          // 16: aibank.core.v1.ListEntriesResponse
	(*Account)(nil),                      // 17: aibank.core.v1.Account
	(*OpenCustomerAccountRequest)(nil),   // 18: aibank.core.v1.OpenCustomerAccountRequest
	(*CreateInternalAccountRequest)(nil), // 19: aibank.core.v1.CreateInternalAccountRequest
	(*GetAccountRequest)(nil),            // 20: aibank.core.v1.GetAccountRequest
	(*GetAccountByIdRequest)(nil),        // 21: aibank.core.v1.GetAccountByIdRequest
	(*Product)(nil),                      // 22: aibank.core.v1.Product
	(*CreateProductRequest)(nil),         // 23: aibank.core.v1.CreateProductRequest
	(*GetProductRequest)(nil),            // 24: aibank.core.v1.GetProductRequest
	(*Finding)(nil),                      // 25: aibank.core.v1.Finding
	(*ListOpenFindingsRequest)(nil),      // 26: aibank.core.v1.ListOpenFindingsRequest
	(*ListOpenFindingsResponse)(nil),     // 27: aibank.core.v1.ListOpenFindingsResponse
	(*ResolveFindingRequest)(nil),        // 28: aibank.core.v1.ResolveFindingRequest
	(*ResolveFindingResponse)(nil),       // 29: aibank.core.v1.ResolveFindingResponse
	(*RunInternalCheckRequest)(nil),      // 30: aibank.core.v1.RunInternalCheckRequest
	(*RunInternalCheckResponse)(nil),     // 31: aibank.core.v1.RunInternalCheckResponse
	(*Authorization)(nil),                // 32: aibank.core.v1.Authorization
	(*AuthorizeRequest)(nil),             // 33: aibank.core.v1.AuthorizeRequest
	(*AuthorizeResponse)(nil),            // 34: aibank.core.v1.AuthorizeResponse
	(*CaptureRequest)(nil),               // 35: aibank.core.v1.CaptureRequest
	(*RefundRequest)(nil),                // 36: aibank.core.v1.RefundRequest
	(*GetAuthorizationRequest)(nil),      // 37: aibank.core.v1.GetAuthorizationRequest
	(*ReleaseExpiredRequest)(nil),        // 38: aibank.core.v1.ReleaseExpiredRequest
	(*ReleaseExpiredResponse)(nil),       // 39: aibank.core.v1.ReleaseExpiredResponse
	(*timestamppb.Timestamp)(nil),        // 40: google.protobuf.Timestamp
}
var file_aibank_core_v1_core_proto_depIdxs = []int32{
	0,  // 0: aibank.core.v1.Entry.direction:type_name -> aibank.core.v1.Direction
	8,  // 1: aibank.core.v1.Entry.amount:type_name -> aibank.core.v1.Money
	9,  // 2: aibank.core.v1.PostRequest.entries:type_name -> aibank.core.v1.Entry
	40, // 3: aibank.core.v1.PostResponse.posted_at:type_name -> google.protobuf.Timestamp
	8,  // 4: aibank.core.v1.GetBalanceResponse.balance:type_name -> aibank.core.v1.Money
	8,  // 5: aibank.core.v1.GetBalanceResponse.projected_balance:type_name -> aibank.core.v1.Money
	0,  // 6: aibank.core.v1.AccountEntry.direction:type_name -> aibank.core.v1.Direction
	8,  // 7: aibank.core.v1.AccountEntry.amount:type_name -> aibank.core.v1.Money
	40, // 8: aibank.core.v1.AccountEntry.posted_at:type_name -> google.protobuf.Timestamp
	14, // 9: aibank.core.v1.ListEntriesResponse.entries:type_name -> aibank.core.v1.AccountEntry
	1,  // 10: aibank.core.v1.Account.type:type_name -> aibank.core.v1.AccountType
	2,  // 11: aibank.core.v1.Account.owner:type_name -> aibank.core.v1.AccountOwner
	3,  // 12: aibank.core.v1.Account.status:type_name -> aibank.core.v1.AccountStatus
	40, // 13: aibank.core.v1.Account.created_at:type_name -> google.protobuf.Timestamp
	1,  // 14: aibank.core.v1.CreateInternalAccountRequest.type:type_name -> aibank.core.v1.AccountType
	5,  // 15: aibank.core.v1.Finding.kind:type_name -> aibank.core.v1.FindingKind
	40, // 16: aibank.core.v1.Finding.created_at:type_name -> google.protobuf.Timestamp
	25, // 17: aibank.core.v1.ListOpenFindingsResponse.findings:type_name -> aibank.core.v1.Finding
	8,  // 18: aibank.core.v1.Authorization.amount:type_name -> aibank.core.v1.Money
	6,  // 19: aibank.core.v1.Authorization.status:type_name -> aibank.core.v1.AuthorizationStatus
	40, // 20: aibank.core.v1.Authorization.expires_at:type_name -> google.protobuf.Timestamp
	40, // 21: aibank.core.v1.Authorization.created_at:type_name -> google.protobuf.Timestamp
	40, // 22: aibank.core.v1.Authorization.settled_at:type_name -> google.protobuf.Timestamp
	40, // 23: aibank.core.v1.Authorization.released_at:type_name -> google.protobuf.Timestamp
	8,  // 24: aibank.core.v1.AuthorizeRequest.amount:type_name -> aibank.core.v1.Money
	32, // 25: aibank.core.v1.AuthorizeResponse.authorization:type_name -> aibank.core.v1.Authorization
	10, // 26: aibank.core.v1.LedgerService.Post:input_type -> aibank.core.v1.PostRequest
	12, // 27: aibank.core.v1.LedgerService.GetBalance:input_type -> aibank.core.v1.GetBalanceRequest
	15, // 28: aibank.core.v1.LedgerService.ListEntries:input_type -> aibank.core.v1.ListEntriesRequest
	18, // 29: aibank.core.v1.AccountService.OpenCustomerAccount:input_type -> aibank.core.v1.OpenCustomerAccountRequest
	19, // 30: aibank.core.v1.AccountService.CreateInternalAccount:input_type -> aibank.core.v1.CreateInternalAccountRequest
	20, // 31: aibank.core.v1.AccountService.GetAccount:input_type -> aibank.core.v1.GetAccountRequest
	21, // 32: aibank.core.v1.AccountService.GetAccountById:input_type -> aibank.core.v1.GetAccountByIdRequest
	23, // 33: aibank.core.v1.ProductService.CreateProduct:input_type -> aibank.core.v1.CreateProductRequest
	24, // 34: aibank.core.v1.ProductService.GetProduct:input_type -> aibank.core.v1.GetProductRequest
	26, // 35: aibank.core.v1.ReconciliationService.ListOpenFindings:input_type -> aibank.core.v1.ListOpenFindingsRequest
	28, // 36: aibank.core.v1.ReconciliationService.ResolveFinding:input_type -> aibank.core.v1.ResolveFindingRequest
	30, // 37: aibank.core.v1.ReconciliationService.RunInternalCheck:input_type -> aibank.core.v1.RunInternalCheckRequest
	33, // 38: aibank.core.v1.AuthorizationService.Authorize:input_type -> aibank.core.v1.AuthorizeRequest
	35, // 39: aibank.core.v1.AuthorizationService.Capture:input_type -> aibank.core.v1.CaptureRequest
	36, // 40: aibank.core.v1.AuthorizationService.Refund:input_type -> aibank.core.v1.RefundRequest
	37, // 41: aibank.core.v1.AuthorizationService.GetAuthorization:input_type -> aibank.core.v1.GetAuthorizationRequest
	38, // 42: aibank.core.v1.AuthorizationService.ReleaseExpired:input_type -> aibank.core.v1.ReleaseExpiredRequest
	11, // 43: aibank.core.v1.LedgerService.Post:output_type -> aibank.core.v1.PostResponse
	13, // 44: aibank.core.v1.LedgerService.GetBalance:output_type -> aibank.core.v1.GetBalanceResponse
	16, // 45: aibank.core.v1.LedgerService.ListEntries:output_type -> aibank.core.v1.ListEntriesResponse
	17, // 46: aibank.core.v1.AccountService.OpenCustomerAccount:output_type -> aibank.core.v1.Account
	17, // 47: aibank.core.v1.AccountService.CreateInternalAccount:output_type -> aibank.core.v1.Account
	17, // 48: aibank.core.v1.AccountService.GetAccount:output_type -> aibank.core.v1.Account
	17, // 49: aibank.core.v1.AccountService.GetAccountById:output_type -> aibank.core.v1.Account
	22, // 50: aibank.core.v1.ProductService.CreateProduct:output_type -> aibank.core.v1.Product
	22, // 51: aibank.core.v1.ProductService.GetProduct:output_type -> aibank.core.v1.Product
	27, // 52: aibank.core.v1.ReconciliationService.ListOpenFindings:output_type -> aibank.core.v1.ListOpenFindingsResponse
	29, // 53: aibank.core.v1.ReconciliationService.ResolveFinding:output_type -> aibank.core.v1.ResolveFindingResponse
	31, // 54: aibank.core.v1.ReconciliationService.RunInternalCheck:output_type -> aibank.core.v1.RunInternalCheckResponse
	34, // 55: aibank.core.v1.AuthorizationService.Authorize:output_type -> aibank.core.v1.AuthorizeResponse
	32, // 56: aibank.core.v1.AuthorizationService.Capture:output_type -> aibank.core.v1.Authorization
	32, // 57: aibank.core.v1.AuthorizationService.Refund:output_type -> aibank.core.v1.Authorization
	32, // 58: aibank.core.v1.AuthorizationService.GetAuthorization:output_type -> aibank.core.v1.Authorization
	39, // 59: aibank.core.v1.AuthorizationService.ReleaseExpired:output_type -> aibank.core.v1.ReleaseExpiredResponse
	43, // [43:60] is the sub-list for method output_type
	26, // [26:43] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_aibank_core_v1_core_proto_init() }
func file_aibank_core_v1_core_proto_init() {
	if File_aibank_core_v1_core_proto != nil {
		return
	}
	file_aibank_core_v1_core_proto_msgTypes[14].OneofWrappers = []any{}
	file_aibank_core_v1_core_proto_msgTypes[15].OneofWrappers = []any{}
	file_aibank_core_v1_core_proto_msgTypes[24].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aibank_core_v1_core_proto_rawDesc), len(file_aibank_core_v1_core_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_aibank_core_v1_core_proto_goTypes,
		DependencyIndexes: file_aibank_core_v1_core_proto_depIdxs,
		EnumInfos:         file_aibank_core_v1_core_proto_enumTypes,
		MessageInfos:      file_aibank_core_v1_core_proto_msgTypes,
	}.Build()
	File_aibank_core_v1_core_proto = out.File
	file_aibank_core_v1_core_proto_goTypes = nil
	file_aibank_core_v1_core_proto_depIdxs = nil
}
