// Contrato del core bancario de AIBank.
//
// Fuente de verdad de la frontera entre el core (Rust) y los adaptadores (Go).
// Un cambio incompatible aquí rompe la compilación de ambos lados, no la producción.
//
// Reglas del contrato:
//   - El dinero SIEMPRE viaja como entero en unidades menores (centavos) + moneda.
//     Nunca punto flotante, nunca decimales en texto.
//   - Toda escritura lleva idempotency_key: los rieles y las redes de tarjetas
//     reintentan, y el efecto debe ocurrir exactamente una vez.
//   - Los errores de negocio viajan con un PostingErrorReason en la metadata
//     `x-aibank-reason`, para que el llamador distinga "fondos insuficientes"
//     (definitivo, no reintentar) de "base no disponible" (reintentable).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: aibank/core/v1/core.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Direction int32

const (
	Direction_DIRECTION_UNSPECIFIED Direction = 0
	Direction_DIRECTION_DEBIT       Direction = 1
	Direction_DIRECTION_CREDIT      Direction = 2
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "DIRECTION_UNSPECIFIED",
		1: "DIRECTION_DEBIT",
		2: "DIRECTION_CREDIT",
	}
	Direction_value = map[string]int32{
		"DIRECTION_UNSPECIFIED": 0,
		"DIRECTION_DEBIT":       1,
		"DIRECTION_CREDIT":      2,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_aibank_core_v1_core_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_aibank_core_v1_core_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{0}
}

type AccountType int32

const (
	AccountType_ACCOUNT_TYPE_UNSPECIFIED AccountType = 0
	AccountType_ACCOUNT_TYPE_ASSET       AccountType = 1
	AccountType_ACCOUNT_TYPE_LIABILITY   AccountType = 2
	AccountType_ACCOUNT_TYPE_EQUITY      AccountType = 3
	AccountType_ACCOUNT_TYPE_INCOME      AccountType = 4
	AccountType_ACCOUNT_TYPE_EXPENSE     AccountType = 5
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0: "ACCOUNT_TYPE_UNSPECIFIED",
		1: "ACCOUNT_TYPE_ASSET",
		2: "ACCOUNT_TYPE_LIABILITY",
		3: "ACCOUNT_TYPE_EQUITY",
		4: "ACCOUNT_TYPE_INCOME",
		5: "ACCOUNT_TYPE_EXPENSE",
	}
	AccountType_value = map[string]int32{
		"ACCOUNT_TYPE_UNSPECIFIED": 0,
		"ACCOUNT_TYPE_ASSET":       1,
		"ACCOUNT_TYPE_LIABILITY":   2,
		"ACCOUNT_TYPE_EQUITY":      3,
		"ACCOUNT_TYPE_INCOME":      4,
		"ACCOUNT_TYPE_EXPENSE":     5,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_aibank_core_v1_core_proto_enumTypes[1].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_aibank_core_v1_core_proto_enumTypes[1]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{1}
}

type AccountOwner int32

const (
	AccountOwner_ACCOUNT_OWNER_UNSPECIFIED AccountOwner = 0
	AccountOwner_ACCOUNT_OWNER_CUSTOMER    AccountOwner = 1
	AccountOwner_ACCOUNT_OWNER_INTERNAL    AccountOwner = 2
)

// Enum value maps for AccountOwner.
var (
	AccountOwner_name = map[int32]string{
		0: "ACCOUNT_OWNER_UNSPECIFIED",
		1: "ACCOUNT_OWNER_CUSTOMER",
		2: "ACCOUNT_OWNER_INTERNAL",
	}
	AccountOwner_value = map[string]int32{
		"ACCOUNT_OWNER_UNSPECIFIED": 0,
		"ACCOUNT_OWNER_CUSTOMER":    1,
		"ACCOUNT_OWNER_INTERNAL":    2,
	}
)

func (x AccountOwner) Enum() *AccountOwner {
	p := new(AccountOwner)
	*p = x
	return p
}

func (x AccountOwner) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountOwner) Descriptor() protoreflect.EnumDescriptor {
	return file_aibank_core_v1_core_proto_enumTypes[2].Descriptor()
}

func (AccountOwner) Type() protoreflect.EnumType {
	return &file_aibank_core_v1_core_proto_enumTypes[2]
}

func (x AccountOwner) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountOwner.Descriptor instead.
func (AccountOwner) EnumDescriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{2}
}

type AccountStatus int32

const (
	AccountStatus_ACCOUNT_STATUS_UNSPECIFIED AccountStatus = 0
	AccountStatus_ACCOUNT_STATUS_ACTIVE      AccountStatus = 1
	AccountStatus_ACCOUNT_STATUS_FROZEN      AccountStatus = 2
	AccountStatus_ACCOUNT_STATUS_CLOSED      AccountStatus = 3
)

// Enum value maps for AccountStatus.
var (
	AccountStatus_name = map[int32]string{
		0: "ACCOUNT_STATUS_UNSPECIFIED",
		1: "ACCOUNT_STATUS_ACTIVE",
		2: "ACCOUNT_STATUS_FROZEN",
		3: "ACCOUNT_STATUS_CLOSED",
	}
	AccountStatus_value = map[string]int32{
		"ACCOUNT_STATUS_UNSPECIFIED": 0,
		"ACCOUNT_STATUS_ACTIVE":      1,
		"ACCOUNT_STATUS_FROZEN":      2,
		"ACCOUNT_STATUS_CLOSED":      3,
	}
)

func (x AccountStatus) Enum() *AccountStatus {
	p := new(AccountStatus)
	*p = x
	return p
}

func (x AccountStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_aibank_core_v1_core_proto_enumTypes[3].Descriptor()
}

func (AccountStatus) Type() protoreflect.EnumType {
	return &file_aibank_core_v1_core_proto_enumTypes[3]
}

func (x AccountStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountStatus.Descriptor instead.
func (AccountStatus) EnumDescriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{3}
}

// Motivo de un rechazo. Viaja en la metadata `x-aibank-reason` junto al código gRPC.
type PostingErrorReason int32

const (
	PostingErrorReason_POSTING_ERROR_REASON_UNSPECIFIED PostingErrorReason = 0
	// La solicitud viola una regla del ledger (desbalance, monto <= 0, moneda).
	PostingErrorReason_POSTING_ERROR_REASON_INVALID PostingErrorReason = 1
	// La clave de idempotencia ya se usó con un payload distinto.
	PostingErrorReason_POSTING_ERROR_REASON_IDEMPOTENCY_CONFLICT PostingErrorReason = 2
	// La cuenta quedaría en negativo y el producto no admite sobregiro.
	PostingErrorReason_POSTING_ERROR_REASON_INSUFFICIENT_FUNDS PostingErrorReason = 3
	// El saldo superaría el tope regulatorio del producto.
	PostingErrorReason_POSTING_ERROR_REASON_BALANCE_CAP_EXCEEDED PostingErrorReason = 4
	// El monto supera el tope por operación del producto.
	PostingErrorReason_POSTING_ERROR_REASON_TRANSACTION_CAP_EXCEEDED PostingErrorReason = 5
)

// Enum value maps for PostingErrorReason.
var (
	PostingErrorReason_name = map[int32]string{
		0: "POSTING_ERROR_REASON_UNSPECIFIED",
		1: "POSTING_ERROR_REASON_INVALID",
		2: "POSTING_ERROR_REASON_IDEMPOTENCY_CONFLICT",
		3: "POSTING_ERROR_REASON_INSUFFICIENT_FUNDS",
		4: "POSTING_ERROR_REASON_BALANCE_CAP_EXCEEDED",
		5: "POSTING_ERROR_REASON_TRANSACTION_CAP_EXCEEDED",
	}
	PostingErrorReason_value = map[string]int32{
		"POSTING_ERROR_REASON_UNSPECIFIED":              0,
		"POSTING_ERROR_REASON_INVALID":                  1,
		"POSTING_ERROR_REASON_IDEMPOTENCY_CONFLICT":     2,
		"POSTING_ERROR_REASON_INSUFFICIENT_FUNDS":       3,
		"POSTING_ERROR_REASON_BALANCE_CAP_EXCEEDED":     4,
		"POSTING_ERROR_REASON_TRANSACTION_CAP_EXCEEDED": 5,
	}
)

func (x PostingErrorReason) Enum() *PostingErrorReason {
	p := new(PostingErrorReason)
	*p = x
	return p
}

func (x PostingErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PostingErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_aibank_core_v1_core_proto_enumTypes[4].Descriptor()
}

func (PostingErrorReason) Type() protoreflect.EnumType {
	return &file_aibank_core_v1_core_proto_enumTypes[4]
}

func (x PostingErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PostingErrorReason.Descriptor instead.
func (PostingErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{4}
}

// Importe monetario. `amount_minor` es siempre positivo en los asientos: el signo
// lo aporta la dirección contable.
type Money struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AmountMinor   int64                  `protobuf:"varint,1,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"` // ISO-4217, 3 letras
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{0}
}

func (x *Money) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *Money) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"` // UUID
	Direction     Direction              `protobuf:"varint,2,opt,name=direction,proto3,enum=aibank.core.v1.Direction" json:"direction,omitempty"`
	Amount        *Money                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{1}
}

func (x *Entry) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Entry) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNSPECIFIED
}

func (x *Entry) GetAmount() *Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

type PostRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Definida por quien origina la operación. Garantiza efecto único.
	IdempotencyKey string `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Naturaleza del movimiento: "deposit", "withdrawal", "p2p_transfer", ...
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// Dos o más asientos que deben balancear por moneda.
	Entries       []*Entry `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	Description   string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostRequest) Reset() {
	*x = PostRequest{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostRequest) ProtoMessage() {}

func (x *PostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostRequest.ProtoReflect.Descriptor instead.
func (*PostRequest) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{2}
}

func (x *PostRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *PostRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PostRequest) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *PostRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	PostedAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=posted_at,json=postedAt,proto3" json:"posted_at,omitempty"`
	// true si la clave ya existía: se devolvió la transacción original sin duplicar.
	Replayed      bool `protobuf:"varint,3,opt,name=replayed,proto3" json:"replayed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostResponse) Reset() {
	*x = PostResponse{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostResponse) ProtoMessage() {}

func (x *PostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostResponse.ProtoReflect.Descriptor instead.
func (*PostResponse) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{3}
}

func (x *PostResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *PostResponse) GetPostedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PostedAt
	}
	return nil
}

func (x *PostResponse) GetReplayed() bool {
	if x != nil {
		return x.Replayed
	}
	return false
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{4}
}

func (x *GetBalanceRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetBalanceResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Balance    *Money                 `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	EntryCount int64                  `protobuf:"varint,2,opt,name=entry_count,json=entryCount,proto3" json:"entry_count,omitempty"`
	// Saldo recalculado desde los asientos. Debe coincidir con `balance`;
	// una discrepancia es un incidente contable.
	ProjectedBalance *Money `protobuf:"bytes,3,opt,name=projected_balance,json=projectedBalance,proto3" json:"projected_balance,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{5}
}

func (x *GetBalanceResponse) GetBalance() *Money {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *GetBalanceResponse) GetEntryCount() int64 {
	if x != nil {
		return x.EntryCount
	}
	return 0
}

func (x *GetBalanceResponse) GetProjectedBalance() *Money {
	if x != nil {
		return x.ProjectedBalance
	}
	return nil
}

type Account struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code            string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type            AccountType            `protobuf:"varint,4,opt,name=type,proto3,enum=aibank.core.v1.AccountType" json:"type,omitempty"`
	Owner           AccountOwner           `protobuf:"varint,5,opt,name=owner,proto3,enum=aibank.core.v1.AccountOwner" json:"owner,omitempty"`
	OwnerId         string                 `protobuf:"bytes,6,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`       // vacío en cuentas internas
	ProductId       string                 `protobuf:"bytes,7,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"` // vacío en cuentas internas
	Currency        string                 `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	Status          AccountStatus          `protobuf:"varint,9,opt,name=status,proto3,enum=aibank.core.v1.AccountStatus" json:"status,omitempty"`
	AllowsOverdraft bool                   `protobuf:"varint,10,opt,name=allows_overdraft,json=allowsOverdraft,proto3" json:"allows_overdraft,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{6}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetType() AccountType {
	if x != nil {
		return x.Type
	}
	return AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *Account) GetOwner() AccountOwner {
	if x != nil {
		return x.Owner
	}
	return AccountOwner_ACCOUNT_OWNER_UNSPECIFIED
}

func (x *Account) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Account) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Account) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Account) GetStatus() AccountStatus {
	if x != nil {
		return x.Status
	}
	return AccountStatus_ACCOUNT_STATUS_UNSPECIFIED
}

func (x *Account) GetAllowsOverdraft() bool {
	if x != nil {
		return x.AllowsOverdraft
	}
	return false
}

func (x *Account) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type OpenCustomerAccountRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Code       string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name       string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CustomerId string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Producto del catálogo del que la cuenta hereda moneda y reglas.
	ProductCode   string `protobuf:"bytes,4,opt,name=product_code,json=productCode,proto3" json:"product_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenCustomerAccountRequest) Reset() {
	*x = OpenCustomerAccountRequest{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenCustomerAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenCustomerAccountRequest) ProtoMessage() {}

func (x *OpenCustomerAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenCustomerAccountRequest.ProtoReflect.Descriptor instead.
func (*OpenCustomerAccountRequest) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{7}
}

func (x *OpenCustomerAccountRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *OpenCustomerAccountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OpenCustomerAccountRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *OpenCustomerAccountRequest) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

type CreateInternalAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          AccountType            `protobuf:"varint,3,opt,name=type,proto3,enum=aibank.core.v1.AccountType" json:"type,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInternalAccountRequest) Reset() {
	*x = CreateInternalAccountRequest{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInternalAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInternalAccountRequest) ProtoMessage() {}

func (x *CreateInternalAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInternalAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateInternalAccountRequest) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{8}
}

func (x *CreateInternalAccountRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateInternalAccountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateInternalAccountRequest) GetType() AccountType {
	if x != nil {
		return x.Type
	}
	return AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *CreateInternalAccountRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{9}
}

func (x *GetAccountRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type Product struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code            string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Currency        string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	AllowsOverdraft bool                   `protobuf:"varint,5,opt,name=allows_overdraft,json=allowsOverdraft,proto3" json:"allows_overdraft,omitempty"`
	// Topes regulatorios; ausentes = sin tope.
	MaxBalanceMinor     *int64 `protobuf:"varint,6,opt,name=max_balance_minor,json=maxBalanceMinor,proto3,oneof" json:"max_balance_minor,omitempty"`
	MaxTransactionMinor *int64 `protobuf:"varint,7,opt,name=max_transaction_minor,json=maxTransactionMinor,proto3,oneof" json:"max_transaction_minor,omitempty"`
	Active              bool   `protobuf:"varint,8,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{10}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Product) GetAllowsOverdraft() bool {
	if x != nil {
		return x.AllowsOverdraft
	}
	return false
}

func (x *Product) GetMaxBalanceMinor() int64 {
	if x != nil && x.MaxBalanceMinor != nil {
		return *x.MaxBalanceMinor
	}
	return 0
}

func (x *Product) GetMaxTransactionMinor() int64 {
	if x != nil && x.MaxTransactionMinor != nil {
		return *x.MaxTransactionMinor
	}
	return 0
}

func (x *Product) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type CreateProductRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Code                string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Currency            string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	AllowsOverdraft     bool                   `protobuf:"varint,4,opt,name=allows_overdraft,json=allowsOverdraft,proto3" json:"allows_overdraft,omitempty"`
	MaxBalanceMinor     *int64                 `protobuf:"varint,5,opt,name=max_balance_minor,json=maxBalanceMinor,proto3,oneof" json:"max_balance_minor,omitempty"`
	MaxTransactionMinor *int64                 `protobuf:"varint,6,opt,name=max_transaction_minor,json=maxTransactionMinor,proto3,oneof" json:"max_transaction_minor,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{11}
}

func (x *CreateProductRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateProductRequest) GetAllowsOverdraft() bool {
	if x != nil {
		return x.AllowsOverdraft
	}
	return false
}

func (x *CreateProductRequest) GetMaxBalanceMinor() int64 {
	if x != nil && x.MaxBalanceMinor != nil {
		return *x.MaxBalanceMinor
	}
	return 0
}

func (x *CreateProductRequest) GetMaxTransactionMinor() int64 {
	if x != nil && x.MaxTransactionMinor != nil {
		return *x.MaxTransactionMinor
	}
	return 0
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_aibank_core_v1_core_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_core_v1_core_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_aibank_core_v1_core_proto_rawDescGZIP(), []int{12}
}

func (x *GetProductRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_aibank_core_v1_core_proto protoreflect.FileDescriptor

const file_aibank_core_v1_core_proto_rawDesc = "" +
	"\n" +
	"\x19aibank/core/v1/core.proto\x12\x0eaibank.core.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"F\n" +
	"\x05Money\x12!\n" +
	"\famount_minor\x18\x01 \x01(\x03R\vamountMinor\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"\x8e\x01\n" +
	"\x05Entry\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x127\n" +
	"\tdirection\x18\x02 \x01(\x0e2\x19.aibank.core.v1.DirectionR\tdirection\x12-\n" +
	"\x06amount\x18\x03 \x01(\v2\x15.aibank.core.v1.MoneyR\x06amount\"\x9d\x01\n" +
	"\vPostRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12/\n" +
	"\aentries\x18\x03 \x03(\v2\x15.aibank.core.v1.EntryR\aentries\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\x8a\x01\n" +
	"\fPostResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x127\n" +
	"\tposted_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bpostedAt\x12\x1a\n" +
	"\breplayed\x18\x03 \x01(\bR\breplayed\"2\n" +
	"\x11GetBalanceRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"\xaa\x01\n" +
	"\x12GetBalanceResponse\x12/\n" +
	"\abalance\x18\x01 \x01(\v2\x15.aibank.core.v1.MoneyR\abalance\x12\x1f\n" +
	"\ventry_count\x18\x02 \x01(\x03R\n" +
	"entryCount\x12B\n" +
	"\x11projected_balance\x18\x03 \x01(\v2\x15.aibank.core.v1.MoneyR\x10projectedBalance\"\x99\x03\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12/\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1b.aibank.core.v1.AccountTypeR\x04type\x122\n" +
	"\x05owner\x18\x05 \x01(\x0e2\x1c.aibank.core.v1.AccountOwnerR\x05owner\x12\x19\n" +
	"\bowner_id\x18\x06 \x01(\tR\aownerId\x12\x1d\n" +
	"\n" +
	"product_id\x18\a \x01(\tR\tproductId\x12\x1a\n" +
	"\bcurrency\x18\b \x01(\tR\bcurrency\x125\n" +
	"\x06status\x18\t \x01(\x0e2\x1d.aibank.core.v1.AccountStatusR\x06status\x12)\n" +
	"\x10allows_overdraft\x18\n" +
	" \x01(\bR\x0fallowsOverdraft\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x88\x01\n" +
	"\x1aOpenCustomerAccountRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12!\n" +
	"\fproduct_code\x18\x04 \x01(\tR\vproductCode\"\x93\x01\n" +
	"\x1cCreateInternalAccountRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12/\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1b.aibank.core.v1.AccountTypeR\x04type\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"'\n" +
	"\x11GetAccountRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\xba\x02\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12)\n" +
	"\x10allows_overdraft\x18\x05 \x01(\bR\x0fallowsOverdraft\x12/\n" +
	"\x11max_balance_minor\x18\x06 \x01(\x03H\x00R\x0fmaxBalanceMinor\x88\x01\x01\x127\n" +
	"\x15max_transaction_minor\x18\a \x01(\x03H\x01R\x13maxTransactionMinor\x88\x01\x01\x12\x16\n" +
	"\x06active\x18\b \x01(\bR\x06activeB\x14\n" +
	"\x12_max_balance_minorB\x18\n" +
	"\x16_max_transaction_minor\"\x9f\x02\n" +
	"\x14CreateProductRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12)\n" +
	"\x10allows_overdraft\x18\x04 \x01(\bR\x0fallowsOverdraft\x12/\n" +
	"\x11max_balance_minor\x18\x05 \x01(\x03H\x00R\x0fmaxBalanceMinor\x88\x01\x01\x127\n" +
	"\x15max_transaction_minor\x18\x06 \x01(\x03H\x01R\x13maxTransactionMinor\x88\x01\x01B\x14\n" +
	"\x12_max_balance_minorB\x18\n" +
	"\x16_max_transaction_minor\"'\n" +
	"\x11GetProductRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code*Q\n" +
	"\tDirection\x12\x19\n" +
	"\x15DIRECTION_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fDIRECTION_DEBIT\x10\x01\x12\x14\n" +
	"\x10DIRECTION_CREDIT\x10\x02*\xab\x01\n" +
	"\vAccountType\x12\x1c\n" +
	"\x18ACCOUNT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ACCOUNT_TYPE_ASSET\x10\x01\x12\x1a\n" +
	"\x16ACCOUNT_TYPE_LIABILITY\x10\x02\x12\x17\n" +
	"\x13ACCOUNT_TYPE_EQUITY\x10\x03\x12\x17\n" +
	"\x13ACCOUNT_TYPE_INCOME\x10\x04\x12\x18\n" +
	"\x14ACCOUNT_TYPE_EXPENSE\x10\x05*e\n" +
	"\fAccountOwner\x12\x1d\n" +
	"\x19ACCOUNT_OWNER_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ACCOUNT_OWNER_CUSTOMER\x10\x01\x12\x1a\n" +
	"\x16ACCOUNT_OWNER_INTERNAL\x10\x02*\x80\x01\n" +
	"\rAccountStatus\x12\x1e\n" +
	"\x1aACCOUNT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ACCOUNT_STATUS_ACTIVE\x10\x01\x12\x19\n" +
	"\x15ACCOUNT_STATUS_FROZEN\x10\x02\x12\x19\n" +
	"\x15ACCOUNT_STATUS_CLOSED\x10\x03*\x9a\x02\n" +
	"\x12PostingErrorReason\x12$\n" +
	" POSTING_ERROR_REASON_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cPOSTING_ERROR_REASON_INVALID\x10\x01\x12-\n" +
	")POSTING_ERROR_REASON_IDEMPOTENCY_CONFLICT\x10\x02\x12+\n" +
	"'POSTING_ERROR_REASON_INSUFFICIENT_FUNDS\x10\x03\x12-\n" +
	")POSTING_ERROR_REASON_BALANCE_CAP_EXCEEDED\x10\x04\x121\n" +
	"-POSTING_ERROR_REASON_TRANSACTION_CAP_EXCEEDED\x10\x052\xa7\x01\n" +
	"\rLedgerService\x12A\n" +
	"\x04Post\x12\x1b.aibank.core.v1.PostRequest\x1a\x1c.aibank.core.v1.PostResponse\x12S\n" +
	"\n" +
	"GetBalance\x12!.aibank.core.v1.GetBalanceRequest\x1a\".aibank.core.v1.GetBalanceResponse2\x96\x02\n" +
	"\x0eAccountService\x12Z\n" +
	"\x13OpenCustomerAccount\x12*.aibank.core.v1.OpenCustomerAccountRequest\x1a\x17.aibank.core.v1.Account\x12^\n" +
	"\x15CreateInternalAccount\x12,.aibank.core.v1.CreateInternalAccountRequest\x1a\x17.aibank.core.v1.Account\x12H\n" +
	"\n" +
	"GetAccount\x12!.aibank.core.v1.GetAccountRequest\x1a\x17.aibank.core.v1.Account2\xaa\x01\n" +
	"\x0eProductService\x12N\n" +
	"\rCreateProduct\x12$.aibank.core.v1.CreateProductRequest\x1a\x17.aibank.core.v1.Product\x12H\n" +
	"\n" +
	"GetProduct\x12!.aibank.core.v1.GetProductRequest\x1a\x17.aibank.core.v1.ProductB3Z1github.com/aibank/aibank/clients/go/corev1;corev1b\x06proto3"

var (
	file_aibank_core_v1_core_proto_rawDescOnce sync.Once
	file_aibank_core_v1_core_proto_rawDescData []byte
)

func file_aibank_core_v1_core_proto_rawDescGZIP() []byte {
	file_aibank_core_v1_core_proto_rawDescOnce.Do(func() {
		file_aibank_core_v1_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aibank_core_v1_core_proto_rawDesc), len(file_aibank_core_v1_core_proto_rawDesc)))
	})
	return file_aibank_core_v1_core_proto_rawDescData
}

var file_aibank_core_v1_core_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_aibank_core_v1_core_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_aibank_core_v1_core_proto_goTypes = []any{
	(Direction)(0),                       // 0: aibank.core.v1.Direction
	(AccountType)(0),                     // 1: aibank.core.v1.AccountType
	(AccountOwner)(0),                    // 2: aibank.core.v1.AccountOwner
	(AccountStatus)(0),                   // 3: aibank.core.v1.AccountStatus
	(PostingErrorReason)(0),              // 4: aibank.core.v1.PostingErrorReason
	(*Money)(nil),                        // 5: aibank.core.v1.Money
	(*Entry)(nil),                        // 6: aibank.core.v1.Entry
	(*PostRequest)(nil),                  // 7: aibank.core.v1.PostRequest
	(*PostResponse)(nil),                 // 8: aibank.core.v1.PostResponse
	(*GetBalanceRequest)(nil),            // 9: aibank.core.v1.GetBalanceRequest
	(*GetBalanceResponse)(nil),           // 10: aibank.core.v1.GetBalanceResponse
	(*Account)(nil),                      // 11: aibank.core.v1.Account
	(*OpenCustomerAccountRequest)(nil),   // 12: aibank.core.v1.OpenCustomerAccountRequest
	(*CreateInternalAccountRequest)(nil), // 13: aibank.core.v1.CreateInternalAccountRequest
	(*GetAccountRequest)(nil),            // 14: aibank.core.v1.GetAccountRequest
	(*Product)(nil),                      // 15: aibank.core.v1.Product
	(*CreateProductRequest)(nil),         // 16: aibank.core.v1.CreateProductRequest
	(*GetProductRequest)(nil),            // 17: aibank.core.v1.GetProductRequest
	(*timestamppb.Timestamp)(nil),        // 18: google.protobuf.Timestamp
}
var file_aibank_core_v1_core_proto_depIdxs = []int32{
	0,  // 0: aibank.core.v1.Entry.direction:type_name -> aibank.core.v1.Direction
	5,  // 1: aibank.core.v1.Entry.amount:type_name -> aibank.core.v1.Money
	6,  // 2: aibank.core.v1.PostRequest.entries:type_name -> aibank.core.v1.Entry
	18, // 3: aibank.core.v1.PostResponse.posted_at:type_name -> google.protobuf.Timestamp
	5,  // 4: aibank.core.v1.GetBalanceResponse.balance:type_name -> aibank.core.v1.Money
	5,  // 5: aibank.core.v1.GetBalanceResponse.projected_balance:type_name -> aibank.core.v1.Money
	1,  // 6: aibank.core.v1.Account.type:type_name -> aibank.core.v1.AccountType
	2,  // 7: aibank.core.v1.Account.owner:type_name -> aibank.core.v1.AccountOwner
	3,  // 8: aibank.core.v1.Account.status:type_name -> aibank.core.v1.AccountStatus
	18, // 9: aibank.core.v1.Account.created_at:type_name -> google.protobuf.Timestamp
	1,  // 10: aibank.core.v1.CreateInternalAccountRequest.type:type_name -> aibank.core.v1.AccountType
	7,  // 11: aibank.core.v1.LedgerService.Post:input_type -> aibank.core.v1.PostRequest
	9,  // 12: aibank.core.v1.LedgerService.GetBalance:input_type -> aibank.core.v1.GetBalanceRequest
	12, // 13: aibank.core.v1.AccountService.OpenCustomerAccount:input_type -> aibank.core.v1.OpenCustomerAccountRequest
	13, // 14: aibank.core.v1.AccountService.CreateInternalAccount:input_type -> aibank.core.v1.CreateInternalAccountRequest
	14, // 15: aibank.core.v1.AccountService.GetAccount:input_type -> aibank.core.v1.GetAccountRequest
	16, // 16: aibank.core.v1.ProductService.CreateProduct:input_type -> aibank.core.v1.CreateProductRequest
	17, // 17: aibank.core.v1.ProductService.GetProduct:input_type -> aibank.core.v1.GetProductRequest
	8,  // 18: aibank.core.v1.LedgerService.Post:output_type -> aibank.core.v1.PostResponse
	10, // 19: aibank.core.v1.LedgerService.GetBalance:output_type -> aibank.core.v1.GetBalanceResponse
	11, // 20: aibank.core.v1.AccountService.OpenCustomerAccount:output_type -> aibank.core.v1.Account
	11, // 21: aibank.core.v1.AccountService.CreateInternalAccount:output_type -> aibank.core.v1.Account
	11, // 22: aibank.core.v1.AccountService.GetAccount:output_type -> aibank.core.v1.Account
	15, // 23: aibank.core.v1.ProductService.CreateProduct:output_type -> aibank.core.v1.Product
	15, // 24: aibank.core.v1.ProductService.GetProduct:output_type -> aibank.core.v1.Product
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_aibank_core_v1_core_proto_init() }
func file_aibank_core_v1_core_proto_init() {
	if File_aibank_core_v1_core_proto != nil {
		return
	}
	file_aibank_core_v1_core_proto_msgTypes[10].OneofWrappers = []any{}
	file_aibank_core_v1_core_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aibank_core_v1_core_proto_rawDesc), len(file_aibank_core_v1_core_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_aibank_core_v1_core_proto_goTypes,
		DependencyIndexes: file_aibank_core_v1_core_proto_depIdxs,
		EnumInfos:         file_aibank_core_v1_core_proto_enumTypes,
		MessageInfos:      file_aibank_core_v1_core_proto_msgTypes,
	}.Build()
	File_aibank_core_v1_core_proto = out.File
	file_aibank_core_v1_core_proto_goTypes = nil
	file_aibank_core_v1_core_proto_depIdxs = nil
}
