// Eventos de dominio del core bancario.
//
// Se emiten mediante el patrón OUTBOX TRANSACCIONAL: el evento se escribe en la
// MISMA transacción de base de datos que los asientos contables. Nunca hay doble
// escritura, así que es imposible que exista un asiento sin su evento o un evento
// de una transacción que se revirtió.
//
// Garantía de entrega: AT-LEAST-ONCE. El relay puede republicar si falla entre
// publicar y marcar. Todo consumidor DEBE deduplicar por `event_id`.
//
// Orden: garantizado por `aggregate_id` (clave de partición en Kafka). No hay
// orden global entre agregados distintos, y no hace falta.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: aibank/events/v1/events.proto

package eventsv1

import (
	corev1 "github.com/aibank/aibank/clients/go/corev1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Asiento tal como quedó registrado, con el saldo resultante de la cuenta.
//
// `balance_after_micros` se incluye deliberadamente: permite que un consumidor
// notifique "recibiste $X, tu saldo es $Y" sin volver a consultar el core, y
// evita que dos eventos concurrentes lean saldos en desorden.
type PostedEntry struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AccountId          string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Direction          corev1.Direction       `protobuf:"varint,2,opt,name=direction,proto3,enum=aibank.core.v1.Direction" json:"direction,omitempty"`
	Amount             *corev1.Money          `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	BalanceAfterMicros int64                  `protobuf:"varint,4,opt,name=balance_after_micros,json=balanceAfterMicros,proto3" json:"balance_after_micros,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PostedEntry) Reset() {
	*x = PostedEntry{}
	mi := &file_aibank_events_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostedEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostedEntry) ProtoMessage() {}

func (x *PostedEntry) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_events_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostedEntry.ProtoReflect.Descriptor instead.
func (*PostedEntry) Descriptor() ([]byte, []int) {
	return file_aibank_events_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *PostedEntry) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *PostedEntry) GetDirection() corev1.Direction {
	if x != nil {
		return x.Direction
	}
	return corev1.Direction(0)
}

func (x *PostedEntry) GetAmount() *corev1.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *PostedEntry) GetBalanceAfterMicros() int64 {
	if x != nil {
		return x.BalanceAfterMicros
	}
	return 0
}

// Una transacción contable quedó asentada en el ledger.
type LedgerTransactionPosted struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identidad del evento. Clave de deduplicación para los consumidores.
	EventId       string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TransactionId string `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	// Clave de idempotencia de la operación que originó el asiento.
	IdempotencyKey string `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// "deposit", "withdrawal", "p2p_transfer", ...
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	Entries       []*PostedEntry         `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	PostedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=posted_at,json=postedAt,proto3" json:"posted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerTransactionPosted) Reset() {
	*x = LedgerTransactionPosted{}
	mi := &file_aibank_events_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerTransactionPosted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerTransactionPosted) ProtoMessage() {}

func (x *LedgerTransactionPosted) ProtoReflect() protoreflect.Message {
	mi := &file_aibank_events_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerTransactionPosted.ProtoReflect.Descriptor instead.
func (*LedgerTransactionPosted) Descriptor() ([]byte, []int) {
	return file_aibank_events_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *LedgerTransactionPosted) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *LedgerTransactionPosted) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *LedgerTransactionPosted) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *LedgerTransactionPosted) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *LedgerTransactionPosted) GetEntries() []*PostedEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *LedgerTransactionPosted) GetPostedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PostedAt
	}
	return nil
}

var File_aibank_events_v1_events_proto protoreflect.FileDescriptor

const file_aibank_events_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x1daibank/events/v1/events.proto\x12\x10aibank.events.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19aibank/core/v1/core.proto\"\xc6\x01\n" +
	"\vPostedEntry\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x127\n" +
	"\tdirection\x18\x02 \x01(\x0e2\x19.aibank.core.v1.DirectionR\tdirection\x12-\n" +
	"\x06amount\x18\x03 \x01(\v2\x15.aibank.core.v1.MoneyR\x06amount\x120\n" +
	"\x14balance_after_micros\x18\x04 \x01(\x03R\x12balanceAfterMicros\"\x8a\x02\n" +
	"\x17LedgerTransactionPosted\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x127\n" +
	"\aentries\x18\x05 \x03(\v2\x1d.aibank.events.v1.PostedEntryR\aentries\x127\n" +
	"\tposted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bpostedAtB7Z5github.com/aibank/aibank/clients/go/eventsv1;eventsv1b\x06proto3"

var (
	file_aibank_events_v1_events_proto_rawDescOnce sync.Once
	file_aibank_events_v1_events_proto_rawDescData []byte
)

func file_aibank_events_v1_events_proto_rawDescGZIP() []byte {
	file_aibank_events_v1_events_proto_rawDescOnce.Do(func() {
		file_aibank_events_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aibank_events_v1_events_proto_rawDesc), len(file_aibank_events_v1_events_proto_rawDesc)))
	})
	return file_aibank_events_v1_events_proto_rawDescData
}

var file_aibank_events_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aibank_events_v1_events_proto_goTypes = []any{
	(*PostedEntry)(nil),             // 0: aibank.events.v1.PostedEntry
	(*LedgerTransactionPosted)(nil), // 1: aibank.events.v1.LedgerTransactionPosted
	(corev1.Direction)(0),           // 2: aibank.core.v1.Direction
	(*corev1.Money)(nil),            // 3: aibank.core.v1.Money
	(*timestamppb.Timestamp)(nil),   // 4: google.protobuf.Timestamp
}
var file_aibank_events_v1_events_proto_depIdxs = []int32{
	2, // 0: aibank.events.v1.PostedEntry.direction:type_name -> aibank.core.v1.Direction
	3, // 1: aibank.events.v1.PostedEntry.amount:type_name -> aibank.core.v1.Money
	0, // 2: aibank.events.v1.LedgerTransactionPosted.entries:type_name -> aibank.events.v1.PostedEntry
	4, // 3: aibank.events.v1.LedgerTransactionPosted.posted_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_aibank_events_v1_events_proto_init() }
func file_aibank_events_v1_events_proto_init() {
	if File_aibank_events_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aibank_events_v1_events_proto_rawDesc), len(file_aibank_events_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aibank_events_v1_events_proto_goTypes,
		DependencyIndexes: file_aibank_events_v1_events_proto_depIdxs,
		MessageInfos:      file_aibank_events_v1_events_proto_msgTypes,
	}.Build()
	File_aibank_events_v1_events_proto = out.File
	file_aibank_events_v1_events_proto_goTypes = nil
	file_aibank_events_v1_events_proto_depIdxs = nil
}
